    var ResourceCN = {
      longitude: 'Долгота (°)',
      latitude: 'Широта (°)',
      altitude: 'Высота (м)',
      login: 'Войти',
      logout: 'Выйти',
      account: 'Мой аккаунт:',
      save: 'Сохранять',
      exit: 'Выйти',
      myMsg: 'Мое сообщение:',
      uploadData: 'Загружать данные',
      name: 'Название',
      address: 'Адрес',
      aqiTitle: 'Запрос индекса PM2.5 в реальном времени',
      onlineTerrain: "Онлайновая топография",
      stkTerrain: 'STK Онлайновая топография',
      tiandituTerrain: 'Тиандиту Онлайновая топография',
      supermapOnlineTerrain: "Cyclone Онлайновая топография",
      title: 'Заголовок',
      confirm: 'Подтвердить',
      cancel: 'Отменять',
      objectEditor: 'Редактирование объектов',
      description: 'Описание',
      compass: 'компас',
      s3mLayer: 'Слой S3M',
      imageryLayer: 'Слой изображения',
      terrainLayer: 'Слой топографической карты',
      sctTerrainLayer: 'Слой топографической карты',
      wmsLayer: 'WMS Услуга',
      wmtsLayer: 'WMTS Услуга',
      arcgisLayer: 'ArcGIS Услуга',
      supermaprestLayer: 'Картографический сервис Cyclone',
      featureQuery: 'Атрибутивный запрос',
      selDataSource: 'Пожалуйста, выберите источник данных',
      selDataSet: 'Пожалуйста, выберите набор данных',
      urlNotNullMsg: 'URL-адрес не может быть пустым, введите URL-адрес!',
      urlErrorMsg: 'Пожалуйста, введите правильный адрес службы!',
      layerNameNotNullMsg: 'Название слоя не может быть пустым, введите название слоя!',
      location: 'Местонахождение',
      notSupportLocation: 'Ваш браузер не поддерживает функцию получения информации о местоположении!',
      layerList: 'Список слоев',
      confirmDelLayer: 'Вы уверены, что хотите удалить слой?',
      DelLayer: 'Удалить слой',
      kmlLayer: 'KML-слой',
      markerLayer: 'MARKER-слой',
      selLocalFile: 'Выберите локальный файл',
      measureArea: 'Измерить площадь',
      measureDis: 'Измерить расстояние',
      measureHeight: 'Измерить высоту',
      pattern: 'Режим рисования：',
      spatialMeasuring: 'Измерение пространства',
      StickMeasurement: 'Наземный расчет',
      heightInterval: 'Контурное расстояние (м):',
      SingleContour: 'Одиночная контурная линия',
      MoreContour: 'Многоконтурная линия',
      measure: 'мера',
      kmUnit: 'километр',
      mUnit: 'метр',
      distance: 'расстояние',
      sqkmUnit: 'квадратный километр',
      sqmUnit: 'квадратный метр',
      area: 'площадь',
      smOnlineService: 'Служба общедоступных данных',
      customService: 'индивидуальный сервис',
      localKML: 'локальные данные',
      portalService: 'мой сервис',
      myScenes: 'моя сцена',
      skyAtmosphereEffect: 'Атмосферный рендеринг',
      sunEffect: 'Рендеринг освещения',
      fogEffect: 'Эффект распыления',
      expand: 'развертывать',
      layerManager: 'управление слоями',
      addLayer: 'Добавить слой',
      setBaseLayer: 'Настройки базовой карты',
      BaseMapImg: 'Базовая карта_img',
      addMarker: 'Добавить MARKER',
      setEffect: 'Настройки рендеринга',
      fold: 'складывать',
      publicService: 'Государственная служба',
      specialEffects: 'спецэффекты',
      HotSpots: 'Горячая точка',
      mycontent: 'Мой контент',
      imgServiceType: 'Изображение (изображение по умолчанию)',
      bingServiceType: 'Глобальная служба изображений BingMap',
      tdtServiceType: 'Глобальный сервис изображений Тиандиту',
      osmServiceType: 'карта openstreetmap',
      tianditu: 'Тиандиту',
      layerExistMsg: 'Слой уже существует, пожалуйста, не загружайте его повторно!',
      imgUrlErrorMsg: 'Ошибка URL сервиса изображений, не удалось загрузить изображение!',
      scpUrlErrorMsg: 'Неверный URL-адрес SCP, и не удалось загрузить слой S3M!',
      visualization: 'Визуализация',
      splitSrc: 'Сравнение рулонных штор',
      animationLand: 'Аномальные изменения температуры земли',
      workspaceSaveOK: 'Рабочая область успешно сохранена!',
      workspaceSaveFail: 'Не удалось сохранить рабочую область',
      depthAgainst: 'Углубленное обнаружение',
      cloud: 'Облака',
      skyBox: 'Скайбокс',
      analysis: 'Трехмерный анализ',
      viewShed: 'Поле зрения',
      showFrame: "Отображать частоту кадров",
      skyline: 'Горизонт',
      sightline: 'Видимость',
      startingInformation: 'Информация о начальной точке',
      endInformation: 'Информация о конечной точке',
      projectImage: 'Доставка видео',
      shadowAnalysis: 'Теневой анализ',
      spacing: 'Расстояние (м)',
      profile: 'Профиль',
      profileInformation: 'Информация профиля',
      ObserverInformation: 'Информация о наблюдателе',
      sceneOptions: 'Свойства сцены',
      otherOptions: 'Другие атрибуты',
      sceneColor: 'Цвет сцены',
      flood: 'Прожектор',
      camera: 'камера',
      about: 'о',
      close: 'закрывать',
      basicOptions: 'Основные атрибуты',
      styleSetting: 'Настройка стиля',
      volumeData: "Объемный рендеринг",
      Setting: 'Настраивать',
      sceneName: 'Название сцены',
      viewMode: 'Режим просмотра',
      multiViewport: 'Разделенный экранный дисплей',
      onePort: 'Не используйте разделенный экран',
      horizontalSnap: 'Горизонтальный разделенный экран',
      verticalSnap: 'Вертикальный разделенный экран',
      tripeSnap: 'Трипснап',
      quadSnap: 'Квадроснап',
      split: 'Эффект затвора',
      splitNONE: 'Отключить рулонные шторы',
      splitLEFT: 'Экранированные рулонные шторы слева',
      splitRIGHT: 'Экранированные рулонные шторы правая',
      splitTop: 'Экранированные рулонные шторы с верхней стороны',
      splitBOTTOM: 'Экранированные рулонные шторы с нижней стороны',
      coordinates: 'Запрос значения координат',
      queryCoordinates: 'Запрос координат (долгота, широта, высота)',
      underground: 'подземный',
      openUnderground: 'Открыть подземку',
      rainAndSnowShow: "Дождь и снег",
      openRainSpecialEffects: 'Включить сцену дождя',
      openSnowSpecialEffects: "Включить снежную сцену",
      rainDensity: "Плотность дождевых капель",
      angle: "Угол падения",
      rainSpeed: "Скорость падения",
      snowDesity: "Плотность снежинок",
      sceneFlood: 'Прожектор сцены',
      openSceneFlood: 'Включить прожектор',
      threshold: 'Порог яркости',
      bloomIntensity: 'Интенсивность света прожектора',
      flyRoute: 'Маршрут полета',
      startFly: 'Начать летать',
      pauseFly: 'Пауза Летать',
      stopFly: 'Остановить летать',
      observe: 'Наблюдать',
      rotate: 'Вращение (°)',
      rotateSpeed: 'Скорость вращения',
      rotatePoint: 'Вращаться вокруг точки',
      cancelRotatePoint: 'Остановить вращение',
      rotateCirculation: 'Цикл',
      restore: "Возобновить вращение",
      interactive: 'Взаимодействовать',
      enableWebcam: 'Включить камеру',
      newContent: 'Обновить содержимое',
      earth: 'Земля',
      shadowMap: 'Тень',
      sun: 'Солнце',
      timeline: 'Временная шкала',
      brightness: 'Яркость',
      contrast: 'Контраст',
      hue: 'Тон',
      saturation: 'Насыщенность',
      gamma: 'гамма',
      RightClickSetS3MLayerProperties: 'Щелкните правой кнопкой мыши, чтобы задать свойства слоя S3M',
      layerOptions: 'Свойства слоя',
      MoveUpOneLevel: 'Переместитесь на один слой вверх',
      MoveDownOneLevel: 'Переместитесь вниз на один слой',
      MoveToTheTop: 'Переместить наверх',
      MoveToTheBottom: 'Переместить в низ',
      visibility: 'видимость',
      layerName: 'Название слоя',
      shadow: 'Тень',
      shadowMode: 'Теневой режим',
      noShadow: 'Нет тени',
      meter: 'метр',
      degree: 'градус',
      setSelectionShadow: 'Показать тень выбранного объекта',
      setShadow: 'Показать все тени объектов',
      shadowDarkness: 'теневой оттенок',
      display: 'Может быть отображен',
      multiSelection: 'множественный выбор',
      cullEnabled: 'двухсторонний рендеринг',
      bReleaseColor: 'Освободить цветовую память',
      visibleDistanceMin: 'Минимальная видимая высота (м)',
      visibleDistanceMax: 'Максимальная видимая высота (м)',
      selectEffect: 'Выбранный эффект',
      selectColorType: 'Выберить цветовой режим',
      mix: 'смесь',
      replace: 'заменять',
      selectColor: 'Выбранный цвет',
      onlyShowSlection: 'Виден только выбранный объект',
      onlyHideSlection: 'Скрыты только выбранные объекты',
      showAll: 'Показать все',
      bottomAltitude: 'Высота дна (м)',
      fillStyle: 'Стиль заполнения',
      fillMode: 'Режим заполнения',
      lineMode: 'Каркасный режим',
      fillAndLine: 'Режимы заливки и каркаса',
      foreColor: 'Цвет переднего плана',
      lineColor: 'Цвет линии',
      direction: 'Направление',
      roll: 'Перевернуть',
      horizontalFov: 'Горизонтальный угол обзора (°)',
      verticalFov: 'Вертикальный угол обзора (°)',
      colorSetting: 'Настройки цвета',
      LineColorSetting: "Настройки цвета линии",
      promptLineColor: 'Цвет линии подсказки',
      visibleColor: 'Цвет видимой области',
      invisibleColor: 'Цвет невидимой области',
      displayVisualsBody: 'Отображать визуальное тело',
      displayInvisibleBody: 'Отображать невидимое тело',
      addViewshed: 'Добавить визуальное поле',
      clear: 'очистить',
      date: 'Выбор даты',
      time: 'время',
      timeInterval: 'временной интервал',
      length: 'Длина (м)',
      width: 'Ширина (м)',
      height: 'Высота (м)',
      firstPoint: 'Первая точка',
      secondPoint: 'Вторая точка',
      thirdPoint: 'Третья точка',
      startTime: 'Время начала',
      endTime: 'Конечное время',
      extrude: 'Протяженность (м)',
      extrudeHeight: 'Высота растяжения (м)',
      sunlight: 'Эффект солнечного света',
      viewPosition: 'Расположение наблюдательного пункта',
      additionalHeight: 'Дополнительная высота (м)',
      visualRange: 'Видимое расстояние (м)',
      directionAngle: 'Угол направления (°)',
      ElevationAngle: 'Угол наклона (°)',
      hideenColor: 'Невидимый цвет',
      addViewPoint: 'Добавить точку наблюдения',
      addTarget: 'Добавить целевую точку',
      displayMode: 'Режим отображения',
      polyline: 'Линейный дисплей',
      polygon: 'Поверхностный дисплей',
      skylinesectorbody: 'Закрытый корпус',
      noOcclusor: 'Нет закрытого корпуса',
      visibleVolume: 'Видимый объем',
      novisibleVolume: 'Невидимый объем ',
      skylineColor: 'Цвет горизонта',
      skylineWidth: 'Ширина горизонта',
      skylineRadius: 'Радиус анализа',
      skyline: 'Горизонт',
      graphDisplay: 'Двумерный дисплей',
      BoxClip: 'Обрезка Box',
      BoxInteractiveClip: 'Интерактивная обрезка Box',
      PlaneClip: 'Плоская резка',
      CrossClip: 'Резка Cross',
      ClipModel: 'Режим обрезки',
      CutInsideBoxFrame: 'Вырезать внутри коробчатой рамы',
      CutOutBoxFrame: 'Вырезать рамку коробки',
      CutInsideBoxNOFrame: 'Вырезать внутри коробки без рамки',
      CutOutBoxNOFrame: 'Вырезать коробки без рамки',
      terrainSlope: 'Направление наклона',
      isoline: 'Контур',
      submergeAnalyze: 'Анализ затопления',
      thematicMapByField: "Тематическая карта поля",
      chooseField: "Выбрать тематические поля",
      BuildingType: "Использование в строительстве",
      BuidlingFloors: "Количество этажей здания",
      house: "Жилой",
      residential: "Коммерческая земля",
      buildingFloor1: "1-9 этажи",
      buildingFloor2: "10-20 этажи",
      buildingFloor3: "Более 20 этажей",
      layerAlpha: "Прозрачность слоя",
      TerrainOperation: 'Эксплуатация на местности',
      terrainModify: 'Изменение рельефа местности',
      operation: "операция",
      modify: 'изменить',
      Excavation: 'Раскопка',
      analyze: 'анализировать',
      eliminate: 'устранять',
      EditingTips: 'Примечание: Нажмите, чтобы выбрать, а затем изменить свойства или очистить',
      TerrainMining: 'Раскопки на местности',
      TerrainMiningDepth: 'Глубина копания (м)',
      analysisArea: 'область анализа',
      SpecifyPolygon: 'Укажить многоугольную область',
      AllRegionsAnalysis: 'Анализ по всем регионам',
      AllRegionsNOAnalysis: 'Все регионы НЕТ анализа',
      SlopeRange: 'Диапазон наклона',
      minimumGrade: 'Минимальный уклон (°)',
      maximumGrade: 'Максимальный наклон (°)',
      displayStyle: 'стиль отображения',
      fill: 'заполнение',
      ShowFillColor: 'показать цвет заливки',
      ShowSlopeArrow: 'Показать стрелку аспекта',
      ShowColorArrow: 'Отображение стрелок цвета и наклона',
      transparency: 'Прозрачность',
      modelTransparency: 'Прозрачность модели',
      SlopeExplain: '(Для анализа уклона требуется обычный рельеф местности)',
      parameterSetting: 'Настройка параметров',
      MaximumVisibleElevation: 'Максимальная видимая высота (м)',
      MinimumVisibleElevation: 'Минимальная видимая высота над уровнем моря (м)',
      PlayerSettings: 'Настройки воспроизведения',
      TheCurrentLevel: 'текущая высота (м)',
      speed: 'скорость (м/с):',
      isolineInterval: 'Эквивалентное расстояние (м)',
      ContourFilling: 'заливка контура',
      panelFilling: 'заливка контура',
      ContourPanelFilling: 'Заполнение контурной линии',
      noColorTable: 'Нет таблицы цветов',
      Add: 'добавить',
      AddPoint: 'Добавить точку',
      AddLine: 'Добавить строку',
      AddFaces: 'добавить лица',
      Thematicmap: 'Тематическая карта',
      symbolicLibrary: 'библиотека символов',
      conversion: 'трансформировать',
      Xrotation: 'Поворот вокруг оси X (°)',
      Yrotation: 'Поворот вокруг оси Y (°)',
      Zrotation: 'Поворот вокруг оси Z (°)',
      Xoffset: "Смещение по оси X",
      Yoffset: "Смещение по оси Y",
      Zoffset: "Смещение по оси Z",
      clearAll: "Очистить все",
      clearChoose: "очистить выбор",
      zoom: 'увеличить',
      Xmobile: 'X мобильный',
      Ymobile: ' мобильный',
      Zmobile: 'Z мобильный',
      delete: 'удалить',
      edit: 'редактировать',
      editZ: 'редактировать Z',
      Zdrection: "Z-направление",
      polylineSymbolLineColor: 'Цвет линии',
      fulline: 'Сплошная линия',
      Virtuallinear: 'Тип пунктирной линии',
      contourline: 'Контурная линия',
      arrowline: 'Линия стрелки',
      Haloline: 'Линия ореола',
      Wakeline: 'Линия пробуждения',
      pureColor: 'Сплошной цвет',
      ThematicmapColor: 'цвет',
      ThematicmapImage: 'картинка',
      gridding: 'сетка',
      stripe: 'полоса',
      serverURl: 'URL службы данных',
      serverExplain: '(адрес службы REST-данных Server публикуется синхронно с моделью)',
      dataset: 'Набор данных',
      DataSourceName: '-----Выбрать название источника данных------',
      DataSetName: '-----Выбрать название источника данных------',
      TheSpaceField: 'Пространственное поле',
      Spacelongitude: 'долгота（°）',
      Spacelatitude: 'широты（°）',
      Spacealtitude: 'Высота (м)',
      StartQuery: 'Запрос',
      CleanCharts: 'Очистить диаграмму',
      reset: 'перезагрузить',
      storage: 'хранение',
      share: 'поделиться',
      sceneSave: 'Сохранение сцены',
      storeDate: 'Срок хранения：',
      scenetag: 'Метка сцены',
      author: 'автор',
      KMLData: 'Локальные данные KML',
      ImageData: 'Местные фотографии',
      OpenLayer: 'Открыть слой',
      OpenScene: 'Открыть сцены',
      scene: 'Сцены',
      clip: 'вырезать',
      terrain: 'местность',
      onlineEditing: 'Онлайн-редактирование',
      wireFrame: "Пограничная линия",
      wireFrameWidth: "Ширина каркаса",
      wireFrameColor: "цвет каркаса",
      interspaceQuery: 'пространственный запрос',
      cameraMinimumZoomDistance: 'Минимальное расстояние масштабирования (метры)',
      highlightBarrier: 'выделять препятствия',
      supermapLogo: 'Логотип IGIT',
      removeInvalidTerrainRegion: 'Удалить недопустимый рельеф',
      polygonSymbolColor: 'цвет символа полигона',
      polylineDashSectionLength: 'длина ломаной линии штрихового сечения',
      polylineTrailPeriod: 'Период следа (секунды)',
      polylineTrailPercent: 'процент прохождения ломаной линии',
      polylineSymbolOutlineWdith: 'Ширина контура (пиксели)',
      pixel: 'пиксель',
      LineWidthPixel: 'Ширина линии в пикселях',
      second: 'секунда',
      PolygonClip: 'Обрезка многоугольника',
      PolygonClipOutside: 'Вырезать внешнюю часть',
      PolygonClipInside: 'Вырезать внутреннюю часть',
      ClipWidth: 'Ширина резки (метры)',
      ClipHeight: 'Высота среза (м)',
      LayerOperation: 'операции со слоями',
      ObliquePhotographyExcavation: 'Наклонная фотография раскопок',
      ExecuteExcavation: 'Выполнить земляные работы',
      ClearExcavation: 'Очистить котлован',
      ObliquePhotographyFlatten: 'Наклонная фотография сглаживается',
      ModelFlatten: 'Модель сглаживается',
      ClearFlatten: 'Очистить сведение',
      showFlyRoute: "показать маршрут полета",
      showFlyStop: "показать сайт полета",
      FloodAnalysis: 'Анализ наводнений',
      MaxHeight: 'Максимальная высота (м)',
      MinHeight: 'Минимальная высота (м)',
      FloodSpeed: 'Скорость погружения (м/с)',
      ExecuteFlood: 'Выполнить флуд',
      ClearFlood: 'Очистить флуд',
      SelectOffset: 'Выберите смещение',
      OpenSelectOffset: 'Включить выбранное смещение',
      OffsetX: 'Смещение по оси X',
      OffsetY: 'Смещение по оси Y',
      offsetZ: 'Смещение по оси Z',
      LayerColor: 'Цвет слоя',
      FillStyleAndWireFrameMode: 'Стиль заливки и каркасный режим',
      FillStyle: 'стиль заливки',
      LayerFillMode: 'Режим заполнения',
      LayerWireframeMode: 'Каркасный режим',
      LayerFillAndWireframeMode: 'Режимы заливки и каркаса',
      TriangleWireframeMode: 'Режим треугольной проволочной рамки', 
      QuadWireframeMode: 'Четырехкаркасный режим',
      SketchWireframeMode: 'Режим каркасного эскиза',
      SpecialEffectsMode: "Каркас со спецэффектами",
      PolygonOffset: 'смещение полигона',
      PolygonOffsetFactor: 'коэффициент смещения',
      PolygonOffsetUnit: 'Единица смещения полигона',
      SceneSave: 'Сохранение сцены',
      SaveDate: 'Срок хранения',
      SceneLabel: 'Метка сцены',
      UpdateCurrentScene: 'Обновить текущую сцену',
      iEarthScene: 'iEarth сцена',
      ShareErrorMsg: 'Не удалось получить информацию о сцене! Сначала войдите в свою учетную запись Portal или Online...',
      ClickToSearchAltitude: 'Нажмите, чтобы запросить высоту',
      UnNamed: 'Безымянный',
      SurfaceTransparency: 'Прозрачность поверхности',
      Version: 'Версия',
      WhatsNew: "1. Добавить функциональный модуль отсечения полигонов\n" +
        "2. Добавить функциональный модуль поперечной резки\n" +
        "3. Слой S3M поддерживает выбор стиля заливки и режима каркаса\n" +
        "4. Слой S3M поддерживает выбранную функцию смещения\n" +
        "5. Слой S3M поддерживает управление цветом модели\n" +
        "6. Слой S3M поддерживает анализ погружения в модели\n" +
        "7. Слой S3M поддерживает функцию смещения полигонов\n" +
        "8. Увеличить ширину контура линейного символа, длину компонента пунктирной линии, период пробуждения и пропорцию настроек параметра пробуждения \n" +
        "9. Поддерживать настройку цвета символа грани \n",
      baseLayerSource: 'Источник базовых карт',
      OnlineBaseMap: 'Онлайновые базовые карты',
      localImage: 'Местные фотографии',
      bingMaps: 'Базовые карты Bing',
      OpenStreetMap: 'Open Street Map',
      SuperMapChinaDark: 'Cyclone China Dark',
      gridImagery: 'Изображение сетки',
      superMapChinaLight: 'Cyclone China Light',
      useRoller: 'Изображение рулонных штор',
      modelRoller: "Модель рулонной шторы",
      lrRoller: 'Рулонные шторы левые и правые',
      leftRoller: 'левый ролик',
      rightRoller: 'правый ролик',
      tbRoller: 'Верхние и нижние рулонные шторы',
      topRoller: 'верхний ролик',
      bottomRoller: 'нижний ролик',
      windParticle: 'частица ветра',
      trailLines: 'линии следов',
      scanLine: 'линия сканирования',
      saveAs: 'Сохранить как',
      saveErrorWhileSceneEmpty: 'Название сохраненной сцены не может быть пустым!',
      saveSceneSuccess: 'Сцена была успешно сохранена!',
      saveSceneFailed: 'Ошибка хранения! Сначала войдите в учетную запись Portal или Online...',
      updateSceneSuccess: 'Сцена успешно обновлена!',
      updateSceneFailed: 'Ошибка обновления сцены, сначала сохраните текущую сцену!',
      layerUrl: 'http://www.supermapol.com/realspace/services/3D-CBD/rest/realspace/datas/Building@CBD/config',
      imageUrl: 'http://www.supermapol.com/realspace/services/3D-zhufeng_new/rest/realspace/datas/image',
      terrainUrl: 'http://www.supermapol.com/realspace/services/3D-zhufeng_new/rest/realspace/datas/terrain',
      sceneUrl: 'http://www.supermapol.com/realspace/services/3D-CBD/rest/realspace',
      fullScreen: 'Полноэкранный режим',
      polygonClipMode: 'Режим обрезки',
      clickToSearchCoordination: 'Щелкните, чтобы запросить значения координат',
      stopChoose: 'Выбор станции',
      stop: 'станция',
      searchPlaceHolder: 'Введите адрес или ориентир...',
      urlMismatchingPattern: 'Пожалуйста, введите правильный формат URL-адреса',
      polygonSymbolGridCellAlpha: 'альфа-ячейка сетки символов полигона',
      polygonSymbolGridLineCount: 'количество линий сетки символов полигона',
      polygonSymbolGridLineThickness: 'толщина линии сетки многоугольного символа',
      polygonSymbolGridLineOffset: 'смещение линии сетки многоугольного символа',
      polygonSymbolStripeEvenColor: 'полоса многоугольного символа ровного цвета',
      polygonSymbolStripeOddColor: 'полоса многоугольного символа нечетного цвета',
      polygonSymbolStripeOffset: 'смещение полосы многоугольного символа',
      polygonSymbolStripeOrientation: 'ориентация полосы многоугольного символа',
      polygonSymbolStripeRepeat: 'повторение полосы многоугольного символа',
      horizontal: 'Горизонтальное направление',
      vertical: 'Вертикальное направление',
      draw: 'рисовать',
      polylineSymbolGapColor: 'Цвет интервала',
      polylineSymbolOutlineColor: 'Цвет контура',
      polylineSymbolGlowPower: 'Сила свечения символа ломаной линии',
      polylineSymbolLineWidth: 'Ширина линии символа полилинии',
      pointSymbolColor: 'цвет точечного символа',
      highlightBarrierColor: 'выделить цвет барьера',
      fullScreenToggle: 'Полноэкранный переключатель',
      light: 'свет',
      ParticleSystem: 'Система частиц',
      Fire: 'пламя',
      Fountain: 'фонтан',
      pointLight: 'точечный свет',
      spotLight: 'прожектор',
      directionalLight: 'Параллельный свет',
      cutoffDistance: 'Диффузионное расстояние',
      decay: 'Коэффициент затухания',
      intensity: 'Интенсивность источника света',
      lightSourceColor: 'Цвет источника света',
      spotLightAngle: 'Диапазон концентрации',
      addToken: 'Добавить token',
      loadException: 'Загрузка происходит ненормально, пожалуйста, проверьте данные или token',
      obliqueLightWarning: 'Примечание: Для данных съемки с наклоном световой эффект отсутствует',
      clickToConfirmThePositionOfTheLightSource: 'Щелкните, чтобы определить местоположение источника света',
      clickLightChangeAttributes: 'Нажмите, чтобы выбрать источник света для изменения свойств',
      ClickLineDirectionLightSource: 'Щелкните по линии, чтобы определить направление источника света',
      hdr: 'Высокий динамический диапазон',
      emissionRate: 'количество',
      particleSize: 'Размер частиц',
      minimumParticleLife: 'Минимальный жизненный цикл',
      maximumParticleLife: 'Максимальный жизненный цикл',
      imumParticleLife: 'жизненный цикл',
      minimumSpeed: 'Минимальная скорость',
      maximumSpeed: 'Максимальная скорость',
      startScale: 'начальная шкала',
      endScale: 'конечная шкала',
      gravity: 'гравитация',
      LaunchType: 'Тип запуска',
      CircularRadiation: 'Круговое излучение',
      SpheroidRadiation: 'Сферическое излучение',
      ConicalRadiation: 'Конусообразное излучение',
      BoxedRadiation: 'Коробчатое излучение',
      TwoDimensionalSkyline: 'Двумерный горизонт',
      SpatialDistance: 'Пространственное расстояние',
      SpaceArea: 'Площадь пространства',
      GroundDistance: 'Расстояние до земли',
      FloorArea: 'Площадь пола',
      projectedArea: 'область тени',
      ellipsoid: 'эллипсоид',
      VerticalHeight: 'высота по вертикали',
      HorizontalDistance: 'Горизонтальное расстояние',
      RoundBall: 'мяч',
      height: 'Высота',
      ShowContour: 'Отображать контурную линию',
      LayerRepeat: 'Слой уже существует, пожалуйста, не загружайте его повторно！',
      SCTFailed: 'URL-адрес SCT неверен, и ландшафт не удалось загрузить!',
      ClickConfirmPoint: 'Нажмите, чтобы подтвердить среднюю точку области операции',
      RightClickEndDrawing: 'Щелкните правой кнопкой мыши, чтобы закончить рисование',
      DrawThreePoints: 'Просто нарисуйте три точки',
      ClickModelAddBox: 'Нажмите на модель, чтобы добавить обтравочную рамку',
      ClickStartDrawing: 'Нажмите, чтобы начать рисовать',
      PleaseDrawCorrectPolygon: 'Пожалуйста, нарисуйте правильный многоугольник',
      LeftClickBottomBox: 'Щелкните левой кнопкой мыши, чтобы начать рисовать прямоугольник в качестве нижней поверхности box.',
      MoveMouseHeightBox: 'Нажмите левую кнопку мыши, чтобы закончить рисование прямоугольника, переместите мышь, чтобы нарисовать высоту box.',
      FloodlightTrail: 'След прожектора',
      WakelineColor: 'Цвет пробуждения',
      airline: 'авиакомпания',
      FloodlightScanLine: 'Линия сканирования прожектора',
      OpenScan: 'Включить сканирование',
      CustomScanDirection: 'Пользовательское направление сканирования',
      CustomScanCenter: 'Пользовательский центр сканирования',
      ScanMode: 'Режим сканирования',
      LineScan: 'Линейное сканирование',
      CircularScan: 'Кольцевое сканирование',
      ScanColor: 'Цвет сканирования',
      ScanTexture: 'Скантекстура',
      LinearTexture1: 'Линейная текстура1',
      LinearTexture2: 'Линейная текстура2',
      CircularTexture1: 'Круглая текстура1',
      CircularTexture2: 'Круглая текстура2',
      HexagonTexture3: 'Текстура шестиугольника3',
      ClickSetScanCenter: 'Нажмите «Установить центр сканирования».',
      ClickSetScanDirection: 'Нажмите, чтобы задать направление сканирования',
      CurrentPointCannotBeSet: 'Текущая точка не может быть установлена',
      ReSetScanCenter: 'Повторно щелкните Установить центр сканирования',
      No: 'Нет',
      ParticleDensity: 'плотность частиц',
      ParticleVelocity: 'скорость частицы',
      Start: 'запускать',
      SwitchData: 'переключать данные',
      PleaseDrawCorrectPolygon: 'сканировать текстуру',
      StretchingHeightZDirection: 'Высота растяжения в направлении Z',
      DrawLine: 'Нарисовать линию',
      Cut: 'Резать',
      Drilling: 'Бурение',
      GeologicalBodyAnalysis: 'Анализ геологического тела',
      ClickDrawFirstPoint: 'Нажмите, чтобы нарисовать первую точку',
      ClickDrawMultiplePointsAndRightClickEnd: 'Щелкните, чтобы нарисовать несколько точек, щелкните правой кнопкой мыши, чтобы завершить',
      DrawTwoPointsAsProfile: 'Нарисуйте две точки одновременно в виде профиля',
      BackLineAnalysis: 'Анализ обратной линии',
      LimitHeightAnalysis: 'Анализ предельной высоты',
      OnLineAnalysis: 'Анализ патч-линий',
      AttachmentRate: 'Скорость прикрепления:0.83',
      ClickLeftAddObservationPoint: 'Щелкните левой кнопкой мыши, чтобы добавить точку наблюдения.',
      ClickLeftAddObMultiplePoints: 'Щелкните левой кнопкой мыши, чтобы добавить несколько целевых точек.',
      chooseLayers: 'выбрать слой',
      ModelSubmergeAnalyze: 'Анализ погружения модели',
      Space: 'пространство',
      Stick: 'Прилипни к земле',
      PostObject: 'вставить объект',
      AddGeometry: 'добавить геометрию',
      Cylinder: 'Цилиндр',
      Cuboid: 'кубоид',
      Ball: 'шар',
      Cone: 'Конус',
      ShortHalfShaft: 'Короткий полуось',
      LongHalfShaft: 'Длинный полуоси',
      StretchingHeight: 'Высота растяжения',
      Granularity: 'Степень детализации',
      Spin: 'спин',
      Xradius: 'X радиус',
      Yradius: 'Y радиус',
      Zradius: 'Z радиус',
      BottomRadius: 'нижний радиус',
      choose: "выбранный режим",
      ZFImagery: 'видео с Эвереста',
      ZFTerrain: 'Местность Эвереста',
      StereographicDrawing: "Стереографический рисунок",
      maxHeight: "Максимальная высота",
      maxDistance: "максимальное расстояние",
      assignRange: "указанный диапазон",
      storageScene: "хранение",
      sceneStorage: "Сохранение сцены",
      openSave: "открытая сцена",
      storageFailed: "Ошибка хранения, сначала войдите в учетную запись Portal или Online...",
      loginSuccess: "успешный вход в систему",
      loginFailed: "Ошибка входа в систему",
      noPermission: "У вас нет разрешения на создание, обновление и удаление сцен",
      accountInfo: "Информация об учетной записи",
      displayCoordinates: 'Отображение координат',
      whiteMold: 'Белая модель',
      whiteMoldMap: 'Тематическая диаграмма белого модуля',
      map: 'Карта',
      service: 'услуга',
      scene: 'Сцены',
      waitData: 'Пожалуйста, дождитесь загрузки данных!',
      notSupport: 'В настоящее время устройство не поддерживает эту функцию',
      downloadAtt: 'Загрузка атрибута',
      serviceName: 'Название службы',
      resourceSubType: 'Подтип ресурса',
      updateTime: 'Время обновления',
      serviceUrl: 'Ссылка на сервис',
      view: 'Проверять',
      noData: 'Нет данных',
      year: 'Год',
      month: 'месяц',
      day: 'день',
      yearsAgo: ' лет назад',
      monthsAgo: ' месяцев назад',
      weeksAgo: ' недель назад',
      daysAgo: ' дней назад',
      hoursAgo: ' часов назад',
      minutesAgo: ' минут назад',
      secondsAgo: ' секунды назад',
      restore: 'восстановить',
      saveAsImage: 'Сохранить как изображение',
      home: 'главная страница',
      japanStand: 'Стандартная карта Японской академии географии',
      japanPale: 'Светлая цветная карта Японской академии географии',
      japanBlank: 'Белая карта Японской академии географии',
      japanImage: 'Карта с изображением Японской академии географии',

      search:"поиск",
      cityList:"Список городов",
      searchBox:"Окно поиска",
      resultNone:"результат Отсутствует",

      
      //新增
      ArcGISMapServer:"ArcGIS картографический сервис",
      ArcGISCSCS2000:"ArcGIS картографический сервис-CSCS2000"
    };

    export default ResourceCN;