    var ResourceEN = {
        longitude: 'Longitude (degree)',
        latitude: 'Latitude (degree)',
        altitude: 'Altitude (m)',
        login: 'Login',
        logout: 'Logout',
        account: 'My Account :',
        save: 'Save',
        exit: 'Exit',
        myMsg: 'My message :',
        uploadData: 'Upload Data',
        name: 'Name',
        address: 'Address',
        aqiTitle: 'PM2.5 index real-time query',
        onlineTerrain: "Online Terrain",
        stkTerrain: 'STK Terrain',
        tiandituTerrain: 'Tianditu Terrain',
        supermapOnlineTerrain: "SuperMap Online Terrain",
        title: 'Title',
        confirm: 'Confirm',
        cancel: 'Cancel',
        objectEditor: 'Object Editor',
        description: 'Description',
        compass: 'Compass',
        s3mLayer: 'S3M Layer',
        imageryLayer: 'Imagery Layer',
        terrainLayer: 'Terrain Layer',
        sctTerrainLayer: 'SCT Terrain layer',
        wmsLayer: 'WMS Layer',
        wmtsLayer: 'WMTS Layer',
        arcgisLayer: 'ArcGIS Tiles Layer',
        supermaprestLayer: 'SuperMap REST Layer',
        featureQuery: 'Attribute Query',
        selDataSource: 'Please select a datasource',
        selDataSet: 'Please select a dataset',
        urlNotNullMsg: 'URL cannot be empty, please enter url!',
        urlErrorMsg: 'Please enter the correct url!',
        layerNameNotNullMsg: 'The layer name cannot be empty, please enter the layer name!',
        location: 'Positioning',
        notSupportLocation: 'Your browser does not support getting location information!',
        layerList: 'Layer List',
        confirmDelLayer: 'Are you sure to delete this layer?',
        DelLayer: 'Delete layer',
        kmlLayer: 'KML layer',
        markerLayer: 'Marker layer',
        selLocalFile: 'Select local file',
        measureArea: 'Measure surface',
        measureDis: 'Measure distance',
        measureHeight: 'Measure height',
        pattern: 'Drawing mode：',
        spatialMeasuring: 'Spatial measurement',
        StickMeasurement: 'Sticking-to-ground Measurement',
        heightInterval: 'Contour height (m):',
        SingleContour: 'Single contour',
        MoreContour: 'Multi-contour',
        measure: 'Measure',
        kmUnit: 'Kilometer',
        mUnit: 'Meter',
        distance: 'Distance',
        sqkmUnit: 'Square kilometer',
        sqmUnit: 'Square meter',
        area: 'Area',
        smOnlineService: 'Public Data Service',
        customService: 'Custom Service',
        portalService: 'My Service',
        localKML: 'Local Data',
        myScenes: 'My Scene',
        skyAtmosphereEffect: 'Sky Atmosphere Effect',
        sunEffect: 'Lighting',
        fogEffect: 'Fog',
        expand: 'Expand',
        layerManager: 'Layer Manager',
        addLayer: 'Add layer',
        setBaseLayer: 'Basemap setting',
        BaseMapImg: 'Image Basemap',
        addMarker: 'Add marker',
        setEffect: 'Rendering setting',
        fold: 'Fold',
        publicService: 'Public Service',
        specialEffects: 'Special effects',
        HotSpots: 'Hot Spots',
        mycontent: 'My content',
        imgServiceType: 'Picture (default image)',
        bingServiceType: 'BingMap global image service',
        tdtServiceType: 'TianDiTu global image service ',
        osmServiceType: 'OpenStreetMap',
        layerExistMsg: 'This layer already exists, don\'t load it again!',
        imgUrlErrorMsg: 'Image service URL is wrong, image loading failed!',
        scpUrlErrorMsg: 'The SCP URL address is wrong, and the S3M layer fails to load!',
        visualization: 'Visualization',
        splitSrc: 'Split contrast',
        animationLand: 'Abnormal changes in land temperature',
        workspaceSaveOK: 'Workspace is saved successfully!',
        workspaceSaveFail: 'Failed to save the workspace',
        depthAgainst: 'Depth',
        cloud: 'Cloud',
        skyBox: 'SkyBox',
        analysis: 'Three-dimensional analysis',
        viewShed: 'Viewshed',
        showFrame: "ShowFrame",
        skyline: 'Skyline analysis',
        sightline: 'Sightline',
        startingInformation: 'Starting point information',
        endInformation: 'Destination information',
        projectImage: 'Video delivery',
        shadowAnalysis: 'Shadow',
        spacing: 'Spacing（m）',
        profile: 'Profile',
        profileInformation: 'Profile information',
        ObserverInformation: 'Observer information',
        sceneOptions: 'Scene properties',
        otherOptions: 'Other attributes',
        sceneColor: 'Scene color',
        flood: 'Floodlight',
        camera: 'Camera',
        about: 'About',
        close: 'Close',
        basicOptions: 'Basic attribute',
        styleSetting: 'Style setting',
        volumeData: "Volume Data",
        Setting: 'Setting',
        sceneName: 'Scene name',
        viewMode: 'View mode',
        multiViewport: 'Multi-viewport',
        onePort: 'Single-viewport',
        horizontalSnap: 'Horizontal split screen',
        verticalSnap: 'Vertical split screen',
        tripeSnap: 'Triple viewport',
        quadSnap: 'Four viewport',
        split: 'Split effect',
        splitNONE: 'Split disabled',
        splitLEFT: 'Shielding split left-side',
        splitRIGHT: 'Shielding split right-side',
        splitTop: 'Shielding split up-side',
        splitBOTTOM: 'Shielding split down-side',
        coordinates: 'Coordinate value query',
        queryCoordinates: 'Query Coordinates',
        underground: 'Underground',
        openUnderground: 'Open underground',
        rainAndSnowShow: "Rain and Snow Show",
        openRainSpecialEffects: 'Open Rain Special Effects',
        openSnowSpecialEffects: "Open Snow Special Effects",
        rainDensity: "Rain Density",
        angle: "Rain Angle",
        rainSpeed: "Rain Speed",
        snowDesity: "Snow Desity",
        sceneFlood: 'Scene Bloom',
        openSceneFlood: 'Bloom Show',
        threshold: 'Brightness threshold',
        Intensity: 'Floodlight intensity',
        flyRoute: 'Fly route',
        startFly: 'Start',
        pauseFly: 'Pause',
        stopFly: 'Stop',
        observe: 'Observe',
        rotate: 'Rotate(degree)',
        rotateSpeed: 'Rotate Speed',
        rotatePoint: 'Rotate Around',
        cancelRotatePoint: 'Cancel Rotate',
        rotateCirculation: 'Cycle',
        restore: "Restore Rotate",
        interactive: 'Interaction',
        enableWebcam: 'Enable camera',
        newContent: 'Update content',
        earth: 'Earth',
        shadowMap: 'Shadow',
        sun: 'Sun',
        timeline: 'Timeline',
        brightness: 'Brightness',
        contrast: 'Contrast',
        hue: 'Hue',
        saturation: 'Saturation',
        gamma: 'Gamma',
        RightClickSetS3MLayerProperties: 'Right-click to set S3M layer properties',
        MoveUpOneLevel: 'Move Up One Level',
        MoveDownOneLevel: 'Move Down One Level',
        MoveToTheTop: 'Move to the Top',
        MoveToTheBottom: 'Move to the Bottom',
        layerOptions: 'Layer properties',
        visibility: 'Visibility',
        layerName: 'Layer name',
        shadow: 'Shadow',
        shadowMode: 'Shadow mode',
        noShadow: 'No shadow',
        meter: 'Meter',
        degree: 'Degree',
        setSelectionShadow: 'Show selected object shadow',
        setShadow: 'Show all object shadows',
        shadowDarkness: 'Shadow shading',
        display: 'Displayable',
        multiSelection: 'Multiple choice',
        cullEnabled: 'Double-sided rendering',
        bReleaseColor: 'Free color memory',
        visibleDistanceMin: 'Minimum visible height(meter)',
        visibleDistanceMax: 'Maximum visible height(meter)',
        selectEffect: 'Select effect',
        selectColorType: 'Select color type',
        mix: 'Mixing',
        replace: 'Replace',
        selectColor: 'Select color',
        onlyShowSlection: 'Only selected objects are visible',
        onlyHideSlection: 'Only selected objects are hidden',
        showAll: 'Show all',
        bottomAltitude: 'Bottom altitude (m)',
        fillStyle: 'Fill style',
        fillMode: 'Fill mode',
        lineMode: 'Wireframe mode',
        fillAndLine: 'Fill and wireframe mode',
        foreColor: 'Foreground',
        lineColor: 'Line color',
        direction: 'Direction',
        roll: 'Roll',
        horizontalFov: 'Horizontal viewing angle (degree)',
        verticalFov: 'Vertical viewing angle (degree)',
        colorSetting: 'Color Setting',
        LineColorSetting: "Line Color Setting",
        promptLineColor: 'Prompt Line Color',
        visibleColor: 'Visible Color',
        invisibleColor: 'Invisible Color',
        displayVisualsBody: 'Display Visual Body',
        displayInvisibleBody: 'Display Invisible Body',
        addViewshed: 'Add a visible field',
        clear: 'Clear',
        date: 'Date selection',
        time: 'Time',
        timeInterval: 'Time Interval',
        length: 'Length(meter)',
        width: 'Width（meter）',
        height: 'Height（meter）',
        firstPoint: 'First point',
        secondPoint: 'Second point',
        thirdPoint: 'Third point',
        startTime: 'Start time',
        endTime: 'End time',
        extrude: 'Extrude(meter)',
        extrudeHeight: 'Stretch height (m)',
        sunlight: 'Sunshine effect',
        viewPosition: 'Observation point position',
        additionalHeight: 'Additional height (m)',
        visualRange: 'Visible distance(m)',
        directionAngle: 'Direction angle (degree)',
        ElevationAngle: 'Pitch angle (degree)',
        hideenColor: 'Invisible color',
        addViewPoint: 'Add observation point',
        addTarget: 'Add target point',
        displayMode: 'Display mode',
        polyline: 'Line display',
        polygon: 'Polygon display',
        skylinesectorbody: 'Closed volume',
        noOcclusor: 'Unclosed volume',
        visibleVolume: 'Visible volume',
        novisibleVolume: 'Invisible volume',
        skylineColor: 'Skyline Color',
        skylineWidth: 'Skyline Width',
        skylineRadius: 'Analysis radius (m)',
        skyline: 'Skyline',
        graphDisplay: '2D Display',
        BoxClip: 'Box clip',
        BoxInteractiveClip: 'Box Interactive Clip',
        PlaneClip: 'Region clip',
        CrossClip: 'Cross clip',
        ClipModel: 'Clip mode',
        CutInsideBoxFrame: 'Clip inside box with wireframe',
        CutOutBoxFrame: 'Clip outside box with wireframe',
        CutInsideBoxNOFrame: 'Clip inside box without wireframe',
        CutOutBoxNOFrame: 'Clip outside box without wireframe',
        terrainSlope: 'Slope aspect',
        isoline: 'Contour',
        submergeAnalyze: 'Submergence analysis',
        thematicMapByField: "Thematic Map by Field",
        chooseField: "Choose Field",
        BuildingType: "Building Type",
        BuidlingFloors: "Buidling Floors",
        house: "House",
        residential: "Residential",
        buildingFloor1: "1-9Floor",
        buildingFloor2: "10-20Floor",
        buildingFloor3: "over 20Floor",
        layerAlpha: "layer Alpha",
        TerrainOperation: 'Terrain Operation',
        terrainModify: 'Terrain Modify',
        operation: "Operation",
        modify: 'Modify',
        Excavation: 'Excavation',
        analyze: 'Analyze',
        eliminate: 'Clear',
        EditingTips: 'Note: click Select to change the attribute or clear',
        TerrainMining: 'Terrain Excavation',
        TerrainMiningDepth: 'Excavation depth (m)',
        analysisArea: 'Analysis area',
        SpecifyPolygon: 'Specify polygon area',
        AllRegionsAnalysis: 'All regions participate in the analysis',
        AllRegionsNOAnalysis: 'All regions do not participate in the analysis',
        SlopeRange: 'Slope interval',
        minimumGrade: 'Minimum slope (degree)',
        maximumGrade: 'Maximum slope (degree)',
        displayStyle: 'Display style',
        fill: 'Filling',
        ShowFillColor: 'Show filling color',
        ShowSlopeArrow: 'Show slope arrow',
        ShowColorArrow: 'Display color and slope arrow',
        transparency: 'Transparency',
        modelTransparency: 'Model Transparency',
        SlopeExplain: '(Slope aspect analysis requires normal terrain)',
        parameterSetting: 'Parameter settings',
        MaximumVisibleElevation: 'Parameter settings',
        MinimumVisibleElevation: 'Minimum visible elevation (m)',
        PlayerSettings: 'Playback setting',
        TheCurrentLevel: 'Current elevation (m)',
        speed: 'Speed (m/s):',
        isolineInterval: 'Isoline Interval (m)',
        ContourFilling: 'Contour filling',
        panelFilling: 'Face filling',
        ContourPanelFilling: 'Contour surface filling',
        noColorTable: 'No color table',
        Add: 'Add',
        AddPoint: 'Add point',
        AddLine: 'Add line',
        AddFaces: 'Add region',
        Thematicmap: 'Thematic Map',
        symbolicLibrary: 'Symbol library',
        conversion: 'Transformation',
        Xrotation: 'Rotate around the X axis(degree)',
        Yrotation: 'Rotate around the Y axis(degree)',
        Zrotation: 'Rotate around the Z axis(degree)',
        Xoffset: "X offset",
        Yoffset: "Y offset",
        Zoffset: "Z offset",
        clearAll: "Clear All",
        clearChoose: "Clear Choose",
        zoom: 'Zoom',
        Xmobile: 'X axis movement',
        Ymobile: 'Y axis movement',
        Zmobile: 'Z axis movement',
        delete: 'Delete',
        edit: 'Edit',
        editZ: 'Edit Z axis',
        Zdrection: "Z Drection",
        polylineSymbolLineColor: 'Line color',
        fulline: 'Solid line',
        Virtuallinear: 'Dotted type',
        contourline: 'Contour line',
        arrowline: 'Arrow line',
        Haloline: 'Halo line',
        Wakeline: 'Tail trace',
        pureColor: 'Solid color',
        ThematicmapColor: 'Color',
        ThematicmapImage: 'Image',
        gridding: 'Grid',
        stripe: 'Stripe',
        serverURl: 'Data service URL',
        serverExplain: '(iserver REST-data service address published synchronously with the model)',
        dataset: 'Dataset',
        DataSourceName: '-----Select datasource name------',
        DataSetName: '-----Select dataset name------',
        TheSpaceField: 'Spatial field',
        Spacelongitude: 'Longitude(degree)',
        Spacelatitude: 'Latitude(degree)',
        Spacealtitude: 'Elevation(meter)',
        StartQuery: 'Start query',
        CleanCharts: 'Clean up the chart',
        home: 'Reset',
        storage: 'Storage',
        share: 'Share',
        sceneSave: 'Scene save',
        storeDate: 'Store date：',
        scenetag: 'Scene label',
        author: 'Author',
        KMLData: 'Local KML data',
        ImageData: 'Image Data',
        OpenLayer: 'Open layer',
        OpenScene: 'Open scene',
        scene: 'Scene',
        clip: 'Clip',
        terrain: 'Terrain',
        onlineEditing: 'Online editing',
        wireFrame: "Wire Frame",
        wireFrameWidth: "Wire Frame Width",
        wireFrameColor: "Wire Frame Color",
        interspaceQuery: 'Spatial query',
        cameraMinimumZoomDistance: 'Camera minimum zoom distance (m)',
        highlightBarrier: 'Highlight obstacle',
        supermapLogo: 'SuperMap Logo',
        removeInvalidTerrainRegion: 'Eliminate invalid terrain regions',
        polygonSymbolColor: 'Polygon symbol color',
        polylineDashSectionLength: 'Dotted component length(pixel)',
        polylineTrailPeriod: 'Tail trace period(second)',
        polylineTrailPercent: 'Polyline trail percent',
        polylineSymbolOutlineWdith: 'Outline width(pixel)',
        pixel: 'Pixel',
        LineWidthPixel: 'Line Width Pixel',
        second: 'Second',
        PolygonClip: 'Polygon clip',
        PolygonClipOutside: 'Clip outside',
        PolygonClipInside: 'Clip interior',
        ClipWidth: 'Clip width(meter)',
        ClipHeight: 'Clip height(meter)',
        LayerOperation: 'Layer operation',
        ObliquePhotographyExcavation: 'Oblique photography excavation',
        ExecuteExcavation: 'Execute excavation',
        ClearExcavation: 'Clear excavation',
        ObliquePhotographyFlatten: 'Oblique photography flatten',
        ModelFlatten: 'Model flatten',
        ClearFlatten: 'Clear flatten',
        showFlyRoute: "Show Fly Route",
        showFlyStop: "Show Fly Stop",
        FloodAnalysis: 'Flood analysis',
        MaxHeight: 'Max height（meter）',
        MinHeight: 'Min height（meter）',
        FloodSpeed: 'Flood speed(m/s)',
        ExecuteFlood: 'Execute flood',
        ClearFlood: 'Clear flood',
        SelectOffset: 'Select offset',
        OpenSelectOffset: 'Open select offset',
        OffsetX: 'Offset X',
        OffsetY: 'Offset Y',
        offsetZ: 'offset Z',
        LayerColor: 'Layer color',
        FillStyleAndWireFrameMode: 'Fill style and wireframe mode',
        FillStyle: 'Fill style',
        LayerFillMode: 'Fill mode',
        LayerWireframeMode: 'Wireframe mode',
        LayerFillAndWireframeMode: 'Fill and wireframe mode',
        TriangleWireframeMode: 'Triangle wireframe',
        QuadWireframeMode: 'Quad wireframe',
        SketchWireframeMode: 'Sketch wireframe',
        SpecialEffectsMode: "Special Effects Mode",
        PolygonOffset: 'Polygon offset',
        PolygonOffsetFactor: 'Polygon offset factor',
        PolygonOffsetUnit: 'Polygon offset unit',
        SceneSave: 'Scene save',
        SaveDate: 'Save date',
        SceneLabel: 'Scene label',
        UpdateCurrentScene: 'Update current scene',
        iEarthScene: 'iEarth scene',
        ShareErrorMsg: 'Get scene failed, please login first...',
        ClickToSearchAltitude: 'Click to search altitude',
        UnNamed: 'Unnamed',
        SurfaceTransparency: 'Surface transparency',
        Version: 'Version',
        WhatsNew: "1、Add the polygon clipping function module\n" +
            "2、Add the Cross clip function module\n" +
            "3、The S3M layer supports fill style and wireframe mode selection\n" +
            "4、The S3M layer allows you to select offsets\n" +
            "5、S3M layer supports model color control\n" +
            "6、The S3M layer supports flooding analysis on the model\n" +
            "7、The S3M layer supports polygon migration\n" +
            "8、Increase the contour width of line symbol, the length of component of dash line, the period of wakes, and the proportion of wakes\n" +
            "9、Support surface symbols to set colors\n",
        baseLayerSource: 'Base layer source',
        OnlineBaseMap: 'Online BaseMap',
        localImage: 'Local Image',
        bingMaps: 'Bing Maps',
        OpenStreetMap: 'OpenStreetMap',
        tianditu: 'Tianditu',
        SuperMapChinaDark: 'SuperMap China Dark',
        gridImagery: 'Grid Imagery',
        superMapChinaLight: 'SuperMap China Light',
        useRoller: 'Image roller',
        modelRoller: "Model roller",
        lrRoller: 'Left-right roller',
        leftRoller: 'Hide left',
        rightRoller: 'Hide right',
        tbRoller: 'Top-bottom roller',
        topRoller: 'Hide top',
        bottomRoller: 'Hide bottom',
        windParticle: 'Wind particle',
        trailLines: 'Trail lines',
        scanLine: 'Scan line',
        saveAs: 'Save as',
        saveErrorWhileSceneEmpty: 'The save scene name cannot be empty!',
        saveSceneSuccess: 'Save scene success！',
        saveSceneFailed: 'Storage scene failed! please login to iPortal or Online account...',
        updateSceneSuccess: 'Scene update success！',
        updateSceneFailed: 'Scene update failed. save the current scene first',
        layerUrl: 'http://www.supermapol.com/realspace/services/3D-CBD/rest/realspace/datas/Building@CBD/config',
        imageUrl: 'http://www.supermapol.com/realspace/services/3D-zhufeng_new/rest/realspace/datas/image',
        terrainUrl: 'http://www.supermapol.com/realspace/services/3D-zhufeng_new/rest/realspace/datas/terrain',
        sceneUrl: 'http://www.supermapol.com/realspace/services/3D-CBD/rest/realspace',
        fullScreen: 'Full screen',
        polygonClipMode: 'Clip mode',
        clickToSearchCoordination: 'Click to search coordination',
        stopChoose: 'Stop choose',
        stop: 'Stop',
        searchPlaceHolder: 'Enter an address or landmark...',
        urlMismatchingPattern: 'Please enter the correct URL format',
        polygonSymbolGridCellAlpha: 'Grid cell alpha',
        polygonSymbolGridLineCount: 'Grid line count',
        polygonSymbolGridLineThickness: 'Grid line thickness',
        polygonSymbolGridLineOffset: 'Grid line offset',
        polygonSymbolStripeEvenColor: 'Even stripe color',
        polygonSymbolStripeOddColor: 'Odd stripe color',
        polygonSymbolStripeOffset: 'Stripe offset',
        polygonSymbolStripeOrientation: 'Stripe orientation',
        polygonSymbolStripeRepeat: 'Stripe repeat',
        horizontal: 'Horizontal',
        vertical: 'Vertical',
        draw: 'Draw',
        polylineSymbolGapColor: 'Gap color',
        polylineSymbolOutlineColor: 'Outline color',
        polylineSymbolGlowPower: 'Glow power',
        polylineSymbolLineWidth: 'Line width(px)',
        pointSymbolColor: 'Point symbol color',
        highlightBarrierColor: 'Highlight barrier color',
        fullScreenToggle: 'Full screen toggle',
        light: 'Light',
        ParticleSystem: 'Particle system',
        Fire: 'Fire',
        Fountain: 'Fountain',
        pointLight: 'Point light',
        spotLight: 'Spot light',
        directionalLight: 'Directional light',
        cutoffDistance: 'Cutoff distance',
        decay: 'Decay',
        intensity: 'Intensity',
        lightSourceColor: 'Light source color',
        spotLightAngle: 'Angle',
        addToken: 'Add token',
        loadException: 'Load failed, please check data or token',
        obliqueLightWarning: 'Note: oblique photographic data has no lighting effect',
        clickToConfirmThePositionOfTheLightSource: 'Click to confirm the position of the light source',
        clickLightChangeAttributes: 'Click to select the light source to change its attributes',
        ClickLineDirectionLightSource: 'Click on the line to determine the direction of the light source',
        hdr: 'High dynamic range',
        emissionRate: 'Emission rate',
        particleSize: 'Particle size',
        minimumParticleLife: 'Minimum particle life',
        maximumParticleLife: 'Maximum particle life',
        imumParticleLife: 'Imum particle life',
        minimumSpeed: 'Minimum speed',
        maximumSpeed: 'Maximum speed',
        startScale: 'Start scale',
        endScale: 'End scale',
        gravity: 'Gravity',
        LaunchType: 'Launch type',
        CircularRadiation: 'Circular radiation',
        SpheroidRadiation: 'Spheroid radiation',
        ConicalRadiation: 'Conical radiation',
        BoxedRadiation: 'Boxed radiation',
        TwoDimensionalSkyline: '2D Skyline',
        SpatialDistance: 'Spatial Distance',
        SpaceArea: 'Space Area',
        GroundDistance: 'Ground Distance',
        FloorArea: 'Floor Area',
        projectedArea: 'Projected Area',
        ellipsoid: 'Ellipsoid',
        RoundBall: 'RoundBall',
        ShowContour: 'Show Contour',
        height: 'Height',
        VerticalHeight: 'Vertical Height',
        HorizontalDistance: 'Horizontal Distance',
        LayerRepeat: 'This layer already exists, please do not load it repeatedly!',
        SCTFailed: 'SCT URL error, terrain loading failed!',
        ClickConfirmPoint: 'Click to confirm the middle point of the operating area',
        RightClickEndDrawing: 'Right click to end drawing',
        DrawThreePoints: 'Draw three points',
        ClickStartDrawing: 'Click to start drawing',
        ClickModelAddBox: 'Click on the model to add a crop box',
        PleaseDrawCorrectPolygon: 'Please draw the correct polygon',
        LeftClickBottomBox: 'Click the left mouse button to start drawing a rectangle as the bottom of the box',
        MoveMouseHeightBox: 'Click the left mouse button to end the rectangle drawing, move the mouse to draw the box height.',
        FloodlightTrail: 'Floodlight Trail',
        WakelineColor: 'Wakeline Color',
        airline: 'Airline',
        FloodlightScanLine: 'Floodlight scan line',
        OpenScan: 'Open Scan',
        CustomScanDirection: 'Custom Scan Direction',
        CustomScanCenter: 'Custom Scan Center',
        ScanMode: 'Scan mode',
        LineScan: 'Line scan',
        CircularScan: 'Circular scan',
        ScanColor: 'Scan color',
        ScanTexture: 'Scan texture',
        LinearTexture1: 'Linear texture 1',
        LinearTexture2: 'Linear texture 2',
        CircularTexture1: 'Circular texture 1',
        CircularTexture2: 'Circular texture 2',
        HexagonTexture3: 'Hexagon texture 3',
        ClickSetScanCenter: 'Click Set Scan Center',
        ClickSetScanDirection: 'Click to set scan direction',
        CurrentPointCannotBeSet: 'Current point cannot be set',
        ReSetScanCenter: 'Re-click Set Scan Center',
        No: 'No',
        ParticleDensity: 'Particle density',
        ParticleVelocity: 'Particle velocity',
        Start: 'Start',
        SwitchData: 'Switch data',
        bloomIntensity: 'Bloom Intensity',
        StretchingHeightZDirection: 'Stretching height in Z direction',
        DrawLine: 'Draw a Line',
        Cut: 'Cut',
        Drilling: 'Drilling',
        GeologicalBodyAnalysis: 'Geological body analysis',
        ClickDrawFirstPoint: 'Click to draw the first point',
        ClickDrawMultiplePointsAndRightClickEnd: 'Click to draw multiple points, right click to end',
        DrawTwoPointsAsProfile: 'Draw two points at a time as a profile',
        BackLineAnalysis: 'Back Line Analysis',
        LimitHeightAnalysis: 'Limit Height Analysis',
        OnLineAnalysis: 'On Line Analysis',
        AttachmentRate: 'Attachment rate:0.83',
        ClickLeftAddObservationPoint: 'Click the left mouse button to add an observation point',
        ClickLeftAddObMultiplePoints: 'Click the left mouse button to add multiple target points',
        chooseLayers: 'Select Layer',
        ModelSubmergeAnalyze: 'Model Flood Analysis',
        Space: 'Space',
        Stick: 'Stick to the ground',
        PostObject: 'Post object',
        AddGeometry: 'Add geometry',
        Cylinder: 'Cylinder',
        Cuboid: 'Cuboid',
        Ball: 'Ball',
        Cone: 'Cone',
        ShortHalfShaft: 'Short half shaft',
        LongHalfShaft: 'Semi-major axis',
        StretchingHeight: 'Stretching height',
        Granularity: 'Granularity',
        Spin: 'Spin',
        Xradius: 'X radius',
        Yradius: 'Y radius',
        Zradius: 'Z radius',
        BottomRadius: 'Bottom Radius',
        choose: "Choose",
        ZFImagery: 'Zhufeng Imagery',
        ZFTerrain: 'Zhufeng Terrain',
        StereographicDrawing: "Stereographic Drawing",
        maxHeight: "Max Height",
        maxDistance: "Max Distance",
        assignRange: "Assign Range",
        storageScene: "Storage Scene",
        sceneStorage: "Scene Storage",
        openSave: "Open Sence",
        storageFailed: "Storage failed. Please log in to your iportal or online account first......",
        loginSuccess: "Login Success",
        loginFailed: "Login Failed",
        noPermission: "You do not have permission to create, update or delete scenes",
        accountInfo: "Account Infomation",
        displayCoordinates: 'Display Coordinates',
        whiteMold: 'White Mold',
        whiteMoldMap: 'White mold thematic map',
        map: 'Map',
        service: 'Service',
        scene: 'Scene',
        waitData: 'Please wait for data loading to complete',
        notSupport: 'The device does not support this function temporarily',
        downloadAtt: 'Attribute Queryable',
        serviceName: 'Service Name',
        resourceSubType: 'Service Type',
        updateTime: 'Update Time',
        serviceUrl: 'Service URL',
        view: 'View',
        noData: 'No data',
        year: 'Year',
        month: 'Month',
        day: 'Day',
        yearsAgo: ' Years Ago',
        monthsAgo: ' Months Ago',
        weeksAgo: ' Weeks Ago',
        daysAgo: ' Days Ago',
        hoursAgo: ' Hours Ago',
        minutesAgo: ' Minutes Ago',
        secondsAgo: ' Seconds Ago',
        restore: 'Restore',
        saveAsImage: 'SaveAsImage',
        home: 'Home',
        japanStand: 'JapanStandMap',
        japanPale: 'JapanPaleMap',
        japanBlank: 'JapanBlankMap',
        japanImage: 'JapanImage',

        search:"search",
        cityList:"List of cities",
        searchBox:"Search box",
        resultNone:"No content temporarily",

        //新增
        ArcGISMapServer:"ArcGIS Map Server",
        ArcGISCSCS2000:"ArcGIS Map Server-CSCS2000"
    };

    export default ResourceEN;