define([],function(){
    var ResourceCN = {
        login : '登陆',
        logout : '登出',
        account : '我的账户 :',
        save : '保存',
        exit : '退出',
        myMsg : '我的消息 :',
        uploadData : '上传数据',
        name : '名称',
        address : '地址',
        aqiTitle : 'PM2.5指数实时查询',
        stkTerrain : 'STK在线地形',
        title : '标题',
        confirm : '确定',
        cancel : '取消',
        objectEditor : '对象编辑',
        description : '描述',
        compass : '罗盘',
        s3mLayer : 'S3M图层',
        imageryLayer : '影像图层',
        terrainLayer : '地形图层',
        sctTerrainLayer : 'SCT地形图层',
        featureQuery : '属性查询',
        selDataSource : '请选择数据源',
        selDataSet : '请选择数据集',
        urlNotNullMsg : 'URL不能为空，请输入url!',
        layerNameNotNullMsg : '图层名称不能为空，请输入图层名称!',
        location : '定位',
        notSupportLocation : '您的浏览器不支持获取位置信息功能！',
        layerList : '图层列表',
        confirmDelLayer : '是否确定删除该图层？',
        kmlLayer : 'KML图层',
        markerLayer : 'MARKER图层',
        selLocalFile : '选择本地文件',
        measureArea : '测面',
        measureDis : '测距',
        measureHeight: '测高',
        close : '关闭',
        measure : '量算',
        kmUnit : '千米',
        mUnit : '米',
        distance : '距离',
        sqkmUnit : '平方公里',
        sqmUnit : '平方米',
        area : '面积',
        smOnlineService : '超图云服务',
        customService : '自定义服务',
        localKML : '本地KML',
        skyAtmosphereEffect : '大气渲染',
        sunEffect : '光照渲染',
        fogEffect : '雾化效果',
        layerManager : '图层管理',
        expand : '展开',
        addLayer : '添加图层',
        setBaseLayer : '底图设置',
        addMarker : '添加MARKER',
        setEffect : '渲染设置',
        fold : '收起',
        publicService : '公共服务',
        specialEffects: '特效',
        mycontent : '我的内容',
        imgServiceType : '图片(默认影像)',
        bingServiceType : 'BingMap全球影像服务',
        tdtServiceType : '天地图全球影像服务',
        osmServiceType : 'openstreetmap地图',
        tianditu : '天地图',
        layerExistMsg : '该图层已经存在，请勿重复加载!',
        imgUrlErrorMsg : '影像服务URL错误，影像加载失败！',
        scpUrlErrorMsg : 'SCP URL地址错误，S3M图层加载失败！',
        visualization:'可视化',
        splitSrc:'卷帘对比',
        animationLand:'陆地温度异常变化',
        workspaceSaveOK : '工作空间保存成功！',
        workspaceSaveFail : '工作空间保存失败',
        depthAgainst : '深度检测',
        analysis : '三维分析',
        viewShed : '可视域分析',
        skyline : '天际线分析',
        sightline : '通视分析',
        projectImage : '视频投放',
        shadowAnalysis : '阴影分析',
        sceneOptions : '场景属性',
        otherOptions : '其他属性',
        close : '关闭',
        basicOptions : '基本属性',
        styleSetting : '风格设置',
        sceneName : '场景名称',
        viewMode : '视图模式',
        multiViewport : '分屏显示',
        onePort : '不使用分屏',
        horizontalSnap : '水平分屏',
        verticalSnap : '垂直分屏',
        tripeSnap : '三视口',
        quadSnap : '四视口',
        earth : '地球',
        shadowMap : '阴影',
        sun : '太阳',
        timeline : '时间轴',
        brightness : '亮度',
        contrast : '对比度',
        hue : '色调',
        saturation : '饱和度',
        gamma : '伽马',
        layerOptions : '图层属性',
        visibility : '可见性',
        layerName : '图层名称',
        shadowMode : '阴影模式',
        noShadow : '无阴影',
        setSelectionShadow : '显示选中对象阴影',
        setShadow :'显示所有对象阴影',
        shadowDarkness : '阴影明暗度',
        display : '可显示',
        multiSelection : '多选择',
        cullEnabled : '双面渲染',
        bReleaseColor :'释放颜色内存',
        visibleDistanceMin : '最小可见高度',
        visibleDistanceMax : '最大可见高度',
        selectColorType : '高亮颜色模式',
        mix : '混合',
        replace : '替换',
        selectColor : '高亮颜色',
        onlyShowSlection : '仅选中对象可见',
        onlyHideSlection : '仅选中对象隐藏',
        showAll : '还原',
        bottomAltitude : '底部高程',
        fillStyle : '填充风格',
        fillMode : '填充模式',
        lineMode : '线框模式',
        fillAndLine : '填充和线框模式',
        foreColor : '前景色',
        lineColor : '线颜色',
        direction : '方向',
        roll : '翻转',
        distance : '距离',
        horizontalFov : '水平视场角',
        verticalFov : '垂直视场角',
        visibleColor : '可见区域颜色',
        invisibleColor : '不可见区域颜色',
        addViewshed : '添加可视域',
        clear : '清除',
        date : '日期选择',
        startTime : '开始时间',
        endTime : '结束时间',        
        extrudeHeight : '拉伸高度',
        shadowAnalysis : '阴影分析',
        sunlight : '日照效果',
        viewPosition : '观察点位置',
        hideenColor : '不可视颜色',
        addViewPoint : '添加观察点',
        addTarget : '添加目标点',
        displayMode : '显示模式',
        polyline : '线显示',
        polygon : '面显示',
        skylineColor : '天际线颜色',
        skylineRadius: '分析半径（米）',
        skyline : '天际线',
        graphDisplay : '二维显示'
    };
    return ResourceCN;
});