define(function(){
    var ResourceJA = {
        longitude : '経度(度)',
        latitude : '緯度(度)',
        altitude : '標高(m)',
        login : 'ログイン',
        logout : 'ログアウト',
        account : 'マイアカウント :',
        save : '保存',
        exit : '閉じる',
        myMsg : 'マイメーセージ :',
        uploadData : 'アップロード',
        name : '名称',
        address : 'アドレス',
        aqiTitle : 'PM2.5リアルタイム検索',
        stkTerrain : 'STKオンライン地形',
        title : 'タイトル',
        confirm : '確認',
        cancel : '取消',
        objectEditor : 'オブジェクト編集',
        description : '説明',
        compass : '方位磁針',
        s3mLayer : 'S3Mレイヤー',
        imageryLayer : '写真レイヤー',
        terrainLayer : '地形レイヤー',
        sctTerrainLayer : 'sct地形レイヤー',
        featureQuery : '属性検索',
        selDataSource : 'データソースを開く',
        selDataSet : 'データセットを開く',
        urlNotNullMsg : 'URLを入力してください',
        layerNameNotNullMsg : 'レイヤー名を入力してください',
        location : '位置情報を取得する',
        notSupportLocation : '位置情報を取得できません',
        layerList : 'レイヤーリスト',
        confirmDelLayer : '選択したレイヤーを削除しますか？',
        kmlLayer : 'KMLレイヤー',
        markerLayer : 'MARKERレイヤー',
        selLocalFile : 'ローカルファイルを開く',
        measureArea : '面積測量',
        measureDis : '距離測量',
        measureHeight: '標高測量',
        pattern : 'パターン：',
        spatialMeasuring : '空間計測',
        StickMeasurement : '地形計測',
        heightInterval: '等高線の間隔(m)：',
        SingleContour : '一つの等高線',
        MoreContour : '複数の等高線',
        close : '完了',
        measure : '計測',
        kmUnit : 'km',
        mUnit : 'm',
        distance : '距離',
        spaceDistance: '空間距離',
        verticalHeight: '垂直距離',
        horizontalDistance: '水平距離',
        sqkmUnit : '平方km',
        sqmUnit : '平方m',
        area : '面積',
        smOnlineService : '公開データサービス',
        customService : 'ユーザー定義サービス',
        localKML : 'ローカルデータ',
        myScenes : 'マイシーン',
        skyAtmosphereEffect : '大気レンダリング',
        sunEffect : '照明レンダリング',
        fogEffect : 'ボリュームレンダリング',
        expand : '展開',
        addLayer : 'レイヤー追加',
        setBaseLayer : '背景レイヤー選択',
        addMarker : 'MARKER追加',
        setEffect : 'レンダリング設定',
        fold : 'たたむ',
        publicService : '公共サービス',
        specialEffects: '特殊効果',
        mycontent : 'マイコンテンツ',
        imgServiceType : '画像(写真)',
        bingServiceType : 'BingMapグローバル写真サービス',
        tdtServiceType : 'Tiandituグローバル写真サービス',
        osmServiceType : 'OpenStreetMap',
        tianditu : 'Tianditu',
        layerExistMsg : '当該レイヤーは存在しています',
        imgUrlErrorMsg : '写真のダウンロードは失敗しました',
        scpUrlErrorMsg : 'SCP URLのエラーにより、S3Mレイヤーを開けません',
        visualization:'可視化',
        splitSrc:'スワイプ比較',
        animationLand:'陸地温度異常変化',
        workspaceSaveOK : 'ワークスペース保存成功',
        workspaceSaveFail : 'ワークスペース保存失敗',
        depthAgainst : '深度検測',
        analysis : '3D解析',
        viewShed : '可視領域',
        skyline : 'スカイライン解析',
        sightline : '見通し',
        startingInformation : '起点情報',
        endInformation : '終点情報',
        projectImage : '動画を投影',
        shadowAnalysis : 'シャドウ',
        profile : '断面',
        ObserverInformation : '観察者情報',
        sceneOptions : 'シーン属性',
        otherOptions : '他の属性',
        sceneColor : 'シーンの色',
        flood : 'フラッド',
        camera : 'カメラ',
        about : 'About',
        close : '閉じる',
        basicOptions : '基本属性',
        styleSetting : 'スタイル属性',
        sceneName : 'シーン名称',
        viewMode : 'ビューモード',
        multiViewport : 'マルチビューポート',
        onePort : 'ワンビューポート',
        horizontalSnap : '左右に配置',
        verticalSnap : '上下に配置',
        tripeSnap : '3つのビューポート',
        quadSnap : '4つのビューポート',
        split : 'スワイプ',
        splitNONE : 'スワイプなし',
        splitLEFT : 'スワイプの左側を非表示',
        splitRIGHT : 'スワイプの右側を非表示',
        splitTop : 'スワイプの上部を非表示',
        splitBOTTOM : 'スワイプの下部を非表示',
        coordinates : '座標',
        queryCoordinates: '座標検索',
        underground : '地下',
        openUnderground: '地下モード有効',
        sceneFlood : 'シーンフラッド',
        openSceneFlood: 'フラッド有効',
        threshold : '明度閾値',
        bloomIntensity : 'フラッド値',
        flyRoute : '飛行ルート',
        startFly : '開始',
        pauseFly : '一時停止',
        stopFly : '停止',
        observe : '観察',
        rotate : '回転（度）',
        rotatePoint : 'ポイント旋回',
        cancelRotatePoint: '旋回停止',
        rotateCirculation : 'ループ',
        interactive : '相互',
        enableWebcam : 'カメラ有効',
        newContent : '内容更新',
        earth : '地球',
        shadowMap : 'シャドウ',
        sun : '太陽',
        timeline : 'タイムライン',
        brightness : '明度',
        contrast : 'コントラスト',
        hue : '色相',
        saturation : '彩度',
        gamma : 'ガンマ',
        layerOptions : 'レイヤー属性',
        visibility : '可視性',
        layerName : 'レイヤー名',
        shadow: 'シャドウ',
        shadowMode : 'シャドウモード',
        noShadow : 'シャドウなし',
        meter : 'm',
        degree : '度',
        setSelectionShadow : '選択オブジェクトのシャドウを表示する',
        setShadow :'シャドウをすべて表示する',
        shadowDarkness : 'シャドウの明度',
        display : '表示可能',
        multiSelection : '複数選択',
        cullEnabled : '両面レンダリング',
        bReleaseColor :'色彩のメモリを解放する',
        visibleDistanceMin : '可視領域の標高-最小（m）',
        visibleDistanceMax : '可視領域の標高-最大（m）',
        selectEffect: '選択オブジェクトの反応',
        selectColorType : '選択オブジェクトの色',
        mix : 'ミックス',
        replace : '置換え',
        selectColor : '色選択',
        onlyShowSlection : '選択オブジェクトのみ可視化',
        onlyHideSlection : '選択オブジェクトのみ隠す',
        showAll : 'すべて表示',
        bottomAltitude : '底の標高(m)',
        fillStyle : 'フィルスタイル',
        fillMode : 'フィルモード',
        lineMode : 'ラインモード',
        fillAndLine : 'フィルとラインモード',
        foreColor : '前景色',
        lineColor : 'ライン色',
        direction : '方位',
        roll : 'ロール',
        distance : '距離',
        horizontalFov : '水平視野角(度)',
        verticalFov : '垂直視野角(度)',
        visibleColor : '可視域の色',
        invisibleColor : '不可視域の色',
        addViewshed : '可視域追加',
        clear : 'クリア',
        date : '日付',
        time : '時間',
        length :'長さ（m）',
        width : '幅（m）',
        height : '高さ（m）',
        firstPoint : '第1点',
        secondPoint : '第2点',
        thirdPoint : '第3点',
        startTime : '開始時間',
        endTime : '完了時間',
        extrude: '伸ばす（m）',
        extrudeHeight : '高さを伸ばす(m)',
        sunlight : '日照の効果',
        viewPosition : '観察ポイント位置',
        additionalHeight : '高さを追加する(m)',
        visualRange : '可視距離（m）',
        directionAngle : '方位角(度)',
        ElevationAngle : '仰俯角(度)',
        hideenColor : '不可視（色）',
        addViewPoint : '観察ポイント追加',
        addTarget : 'ターゲットポイント追加',
        displayMode : '表示パターン',
        polyline : 'ライン表示',
        polygon : 'ポリゴン表示',
        skylinesectorbody : '閉じたポリゴン',
        noOcclusor : '閉じていないポリゴン',
        visibleVolume : '可視ボリューム',
        novisibleVolume: '不可視ボリューム',
        skylineColor : 'スカイライン(色)',
        skylineRadius: '半径（m）',
        skyline : 'スカイライン',
        graphDisplay : '2D表示',
        BoxClip : 'Boxトリミング',
        PlaneClip : '平面トリミング',
        CrossClip : 'Crossトリミング',
        ClipModel : 'トリミングモード',
        CutInsideBoxFrame : 'ボックス内側でトリミング',
        CutOutBoxFrame : 'ボックス外側でトリミング',
        CutInsideBoxNOFrame : '内側でトリミング',
        CutOutBoxNOFrame : '外側でトリミング',
        terrainSlope : '傾斜角',
        isoline : '等値線',
        submergeAnalyze : '浸水解析',
        TerrainOperation : '地形操作',
        TilesetEditor : '地形編集',
        analyze : '解析',
        eliminate : 'クリア',
        TerrainMining : '地形掘削',
        TerrainMiningDepth : '掘削深度(m)',
        analysisArea : '解析領域',
        SpecifyPolygon : '特定ポリゴン範囲',
        AllRegionsAnalysis : '全範囲を解析する',
        AllRegionsNOAnalysis : '全範囲を解析しません',
        SlopeRange : '傾斜角範囲',
        minimumGrade : '最小傾斜角(度)',
        maximumGrade : '最大傾斜角(度)',
        displayStyle : '表示スタイル',
        fill : 'フィル',
        ShowFillColor : 'フィル色を表示する',
        ShowSlopeArrow : '傾斜方向のシンボル表示',
        ShowColorArrow : '色と傾斜方向のシンボル表示',
        transparency : '透明度',
        modelTransparency: 'モード透明度',
        SlopeExplain : '(傾斜角解析には法線情報を持つ地形が必要)',
        parameterSetting : 'パラメーター設定',
        MaximumVisibleElevation : '最大表示高度(m)',
        MinimumVisibleElevation : '最小表示高度(m)',
        PlayerSettings : '初期設定',
        TheCurrentLevel : '現時点の高度(m)',
        speed : '速度(m/s):',
        isolineInterval : '等高線の間隔(m)',
        ContourFilling : '等高線フィル',
        panelFilling : '等高面フィル',
        ContourPanelFilling : '等高線面フィル',
        noColorTable : 'カラーなしテーブル',
        Add : '追加',
        AddPoint : 'ポイント追加',
        AddLine : 'ライン追加',
        AddFaces : 'ポリゴン追加',
        symbolicLibrary : 'シンボルライブラリ',
        conversion : '変換',
        Xrotation : 'X軸周り（度）',
        Yrotation : 'Y軸周り（度）',
        Zrotation : 'Z軸周り（度）',
        zoom : 'ズーム',
        delete : '削除',
        polylineSymbolLineColor : 'ラインのカラー',
        fulline : '実線',
        Virtuallinear : '点線',
        contourline : '輪郭線',
        arrowline : '矢線',
        Haloline : '円光線',
        Wakeline : '軌跡線',
        pureColor : '純色',
        gridding : 'グリッド',
        stripe : 'ストライプ',
        serverURl : 'データサービスURL',
        serverExplain : '(iserver REST-データサービスアドレス)',
        dataset : 'データソース、データセット',
        DataSourceName : '-----データソースを開く------',
        DataSetName : '-----データセットを開く------',
        TheSpaceField : '空間フィールド',
        Spacelongitude : '経度（度）',
        Spacelatitude : '緯度（度）',
        Spacealtitude : '標高（m）',
        StartQuery : 'クエリ開始',
        CleanCharts : '図表をクリア',
        home : 'リセット',
        storage : '保存',
        share : 'シェア',
        sceneSave : 'シーンを保存',
        storeDate : '日付を保存：',
        scenetag : 'シーンのタグ',
        author : '作成者',
        KMLData : 'ローカルKMLデータ',
        OpenLayer : 'レイヤーを開く',
        OpenScene : 'シーンを開く',
        scene : 'シーン',
        clip : 'クリップ',
        terrain : '地形',
        onlineEditing : 'オンラインで編集',
        interspaceQuery: '空間検索',
        cameraMinimumZoomDistance: '最小縮小距離(m)',
        highlightBarrier: '障害物を提示する',
        supermapLogo: 'スーパマップロゴ',
        removeInvalidTerrainRegion: 'エラーの地形を無効にする',
        polygonSymbolColor: 'ポリゴンの色',
        polylineDashSectionLength: '点線設定（pix）',
        polylineTrailPeriod: '軌跡線の存在時間（秒）',
        polylineTrailPercent: '軌跡線の割合',
        polylineSymbolOutlineWdith: '輪郭の幅（pix）',
        pixel: 'ピクセル(pix)',
        second: '秒',
        PolygonClip: '多角形ポリゴンをクリップ',
        PolygonClipOutside: '外側をクリップ',
        PolygonClipInside: '内側をクリップ',
        ClipWidth: 'クリップの幅（m）',
        ClipHeight: 'クリップの高さ（m）',
        LayerOperation: 'レイヤーの操作',
        ObliquePhotographyExcavation: 'モデル掘削',
        ExecuteExcavation: '掘削開始',
        ClearExcavation: '掘削をクリア',
        ObliquePhotographyFlatten: 'モデルモザイク',
        ModelFlatten: 'モデルモザイク',
        ClearFlatten: 'モザイクをクリア',
        FloodAnalysis: '浸水解析',
        MaxHeight: '最大高度（m）',
        MinHeight: '最小高度（m）',
        FloodSpeed: '浸水速度(m/秒)',
        ExecuteFlood: '浸水開始',
        ClearFlood: '浸水をクリア',
        SelectOffset: '選択オブジェクトのオフセット',
        OpenSelectOffset: '選択オブジェクトのオフセット有効',
        OffsetX: 'X軸周りオフセット',
        OffsetY: 'Y軸周りオフセット',
        offsetZ: 'Z軸周りオフセット',
        LayerColor: 'レイヤーの色',
        FillStyleAndWireFrameMode: 'フィルスタイルとワイヤーフレームモード',
        FillStyle: 'フィルスタイル',
        WireFrameMode: 'ワイヤーフレームモード',
        LayerFillMode: 'フィルモード',
        LayerWireframeMode: 'ワイヤーフレームモード',
        LayerFillAndWireframeMode: 'フィルとワイヤーフレームモード',
        TriangleWireframeMode: '三角面ワイヤーフレーム',
        QuadWireframeMode: '四角面ワイヤーフレーム',
        SketchWireframeMode: 'スケッチモード',
        PolygonOffset: '多角形のオフセット',
        PolygonOffsetFactor: 'オフセット因子',
        PolygonOffsetUnit: 'オフセット単位',
        SceneSave: 'シーンの保存',
        SaveDate: '保存データ',
        SceneName: 'シーン名',
        SceneLabel: 'シーンタブ',
        UpdateCurrentScene: '現在シーンを更新',
        iEarthScene: 'iEarthシーン',
        ShareErrorMsg: 'シーン情報を取得できません。iPortalまたはOnlineにログインしてください...',
        ClickToSearchAltitude: '選択して高度検索',
        UnNamed: '名前なし',
        SurfaceTransparency: '地表透明度',
        Version: 'バージョン',
        WhatsNew: "1、多角形クリップモジュール追加\n"+
        "2、クロスクリップモジュール追加\n"+
        "3、S3Mレイヤーはフィルスタイルとワイヤーフレームモードをサポート\n"+
        "4、S3Mレイヤーは選択オブジェクトのオフセット機能をサポート\n"+
        "5、S3Mレイヤーはモデル色コントロール機能をサポート\n"+
        "6、S3Mレイヤーは浸水解析モジュールをサポート\n"+
        "7、S3Mレイヤーは多角形のオフセット機能をサポート\n"+
        "8、ライン輪郭の設定、点線の設定、軌跡線の設定を追加\n"+
        "9、ポリゴンシンボルの色設定をサポート\n",
        baseLayerSource: '背景画像',
        localImage: 'ローカル画像',
        bingMaps: 'BingMap',
        tianditu: 'Tianditu',
        OpenStreetMap: 'Open Street Map',
        SuperMapChinaDark: 'SuperMap China Dark',
        gridImagery: 'グリッド画像',
        superMapChinaLight: 'SuperMap China Light',
        useRoller: 'スワイプ使用',
        lrRoller: '左右に配置',
        leftRoller: '左側を非表示',
        rightRoller: '右側を非表示',
        tbRoller: '上下に配置',
        topRoller: '上部を非表示',
        bottomRoller: '下部を非表示',
        imageryRoller: '画像スワイプ',
        windParticle: '風力場',
        trailLines: '軌跡線',
        scanLine: 'スキャン線',
        saveAs: '名前をつけて保存',
        saveErrorWhileSceneEmpty: 'シーン名を設定してください',
        saveSceneSuccess: 'シーンを保存しました',
        saveSceneFailed: '保存失敗、iPortalまたはOnlineにログインしてください...',
        updateSceneSuccess: 'シーンを更新しました',
        updateSceneFailed: 'シーンの更新が失敗した，更新する前に保存してください',
        layerUrl: 'レイヤーURL',
        layerName: 'レイヤー名',
        sceneUrl: 'シーンURL',
        fullScreen: '最大化',
        polygonClipMode: 'クリップモード',
        clickToSearchCoordination: '選択したオブジェクトの座標値を検索',
        stop: 'サイト',
        stopChoose: 'ポイントを選択',
        searchPlaceHolder: 'キーワードを入力してください...',
        urlMismatchingPattern: '正しいURLを入力してください',
        polygonSymbolGridCellAlpha: 'ユニット透明度',
        polygonSymbolGridLineCount: 'グリッド密度',
        polygonSymbolGridLineThickness: 'グリッド線の幅',
        polygonSymbolGridLineOffset: 'グリッド線のムーブ',
        polygonSymbolStripeEvenColor: '偶数のストライプが色付き',
        polygonSymbolStripeOddColor: '奇数のストライプが色付き',
        polygonSymbolStripeOffset: 'ストライプのオフセット量',
        polygonSymbolStripeOrientation: 'ストライプの向き',
        polygonSymbolStripeRepeat: 'ストライプの反復数',
        horizontal: '水平方向',
        vertical: '垂直方向',
        draw: '描画',
        polylineSymbolGapColor: '間隔の色彩',
        polylineSymbolOutlineColor: '輪郭の色彩',
        polylineSymbolGlowPower: '円光の強度',
        polylineSymbolLineWidth: '線の幅（pix）',
        pointSymbolColor: 'ポイントシンボルの色',
        highlightBarrierColor: '障害物をハイライト',
        fullScreenToggle: '全画面切替',
        light: 'ライト',
        pointLight: 'ポイントライト',
        spotLight: 'スポットライト',
        directionalLight: '平行ライト',
        cutoffDistance: '拡散距離',
        decay: '減衰因子',
        intensity: '光の強度',
        lightSourceColor: '光の色',
        spotLightAngle: 'スポットライトの範囲',
        addToken: 'トークン追加',
        loadException: 'ロードの異常。データやトークンを確認してください',
        obliqueLightWarning: '※3Dタイルキャッシュレイヤーには光効果がありません',
        hdr: 'ハイダイナミックレンジ',
        accessSceneFailedWithoutPermission: 'ログインしてください',
        accessSceneFailedNoScene: '目標のシーンが開けません',
        Setting : '設定',
        Thematicmap : '主題図',
        ThematicmapColor : '色彩',
        ThematicmapImage : '画像',
        gridding : 'グリッド',
        ImageData : 'ローカル画像',
        ParticleSystem: '粒子',
        Fire:'火炎',
        Fountain:'噴水',
        emissionRate:'数量',
        particleSize:'粒子サイズ',
        minimumParticleLife:'最短存在時間',
        maximumParticleLife:'最長存在時間',
        minimumSpeed:'最小速度',
        maximumSpeed:'最大速度',
        startScale:'初期縮尺',
        endScale:'最終縮尺',
        gravity:'重力',
        LaunchType:'放射タイプ',
        CircularRadiation:'円形放射',
        SpheroidRadiation:'楕円体放射',
        ConicalRadiation:'円錐放射',
        BoxedRadiation:'箱状放射',
        TwoDimensionalSkyline:'2Dスカイライン',
        LayerRepeat:'当レイヤーは存在しています',
        SCTFailed:'SCTのURLがエラー。地形ロードに失敗。',
        RightClickToDisplay:'このレイヤーのプロパティを右クリックして表示/設定します。',
        notSupportTerrain:'注：地形はしばらくサポートしていません。'
    };
    return ResourceJA;
});