define(function(){
    var ResourceEN = {
        longitude : 'Longitude (degrees)',
        latitude : 'Latitude (degrees)',
        altitude : 'Altitude (m)',
        login : 'Log in',
        logout : 'Log out',
        account : 'My account :',
        save : 'Save',
        exit : 'Exit',
        myMsg : 'My message :',
        uploadData : 'Upload Data',
        name : 'Name',
        address : 'Address',
        aqiTitle : 'PM2.5 index real-time query',
        stkTerrain : 'STK online terrain',
        title : 'Title',
        confirm : 'Confirm',
        cancel : 'Cancel',
        objectEditor : 'Object editor',
        description : 'Description',
        compass : 'Compass',
        s3mLayer : 'S3M Layer',
        imageryLayer : 'Imagery Layer',
        terrainLayer : 'Terrain layer',
        sctTerrainLayer : 'terrain layer',
        featureQuery : 'Attribute query',
        selDataSource : 'Please select a datasource',
        selDataSet : 'Please select a dataset',
        urlNotNullMsg : 'URL cannot be empty, please enter url!',
        layerNameNotNullMsg : 'The layer name cannot be empty, please enter the layer name!',
        location : 'Positioning',
        notSupportLocation : 'Your browser does not support getting location information!',
        layerList : 'Layer list',
        confirmDelLayer : 'Are you sure to delete this layer?',
        kmlLayer : 'KML layer',
        markerLayer : 'MARKER layer',
        selLocalFile : 'Select local file',
        measureArea : 'Measure surface',
        measureDis : 'Measure distance',
        measureHeight: 'Measure height',
        pattern : 'Drawing mode：',
        spatialMeasuring : 'Spatial measurement',
        StickMeasurement : 'Sticking-to-ground Measurement',
        heightInterval: 'Contour height (m):',
        SingleContour : 'Single contour',
        MoreContour : 'Multi-contour',
        close : 'Close',
        measure : 'Measure',
        kmUnit : 'kilometer',
        mUnit : 'Meter',
        distance : 'Distance',
        spaceDistance: 'Space Distance',
        verticalHeight: 'Vertical Height',
        horizontalDistance: 'Horizontal Distance',
        sqkmUnit : 'Square kilometer',
        sqmUnit : 'Square meter',
        area : 'Area',
        smOnlineService : 'Public data service',
        customService : 'Custom service',
        localKML : 'Local data',
        myScenes : 'My scene',
        skyAtmosphereEffect : 'Atmospheric rendering',
        sunEffect : 'Lighting rendering',
        fogEffect : 'Atomization effect',
        expand : 'Expand',
        addLayer : 'Add layer',
        setBaseLayer : 'Basemap settings',
        addMarker : 'Add MARKER',
        setEffect : 'Rendering settings',
        fold : 'Fold',
        publicService : 'Public Service',
        specialEffects: 'Special effects',
        mycontent : 'My content',
        imgServiceType : 'Picture (default image)',
        bingServiceType : 'BingMap global imaging service',
        tdtServiceType : 'Tianditu global image service ',
        osmServiceType : 'openstreetmap',
        tianditu : 'Tianditu',
        layerExistMsg : 'This layer already exists, don\'t load it again!',
        imgUrlErrorMsg : 'Image service URL is wrong, image loading failed!',
        scpUrlErrorMsg : 'The SCP URL address is incorrect, and the S3M layer fails to load!',
        visualization:'Visualization',
        splitSrc:'Split contrast',
        animationLand:'Abnormal changes in land temperature',
        workspaceSaveOK : 'Workspace is saved successfully!',
        workspaceSaveFail : 'Failed to save the workspace',
        depthAgainst : 'Depth detection',
        analysis : 'Three-dimensional analysis',
        viewShed : 'Viewshed',
        skyline : 'Skyline analysis',
        sightline : 'Sightline',
        startingInformation : 'Starting point information',
        endInformation : 'Destination information',
        projectImage : 'Video delivery',
        shadowAnalysis : 'Shadow',
        profile : 'Profile',
        ObserverInformation : 'Observer information',
        sceneOptions : 'Scene properties',
        otherOptions : 'Other attributes',
        sceneColor : 'Scene color',
        flood : 'Floodlight',
        camera : 'Camera',
        about : 'About',
        basicOptions : 'Basic attribute',
        styleSetting : 'Style setting',
		Setting : 'Setting',
        sceneName : 'Scene name',
        viewMode : 'View mode',
        multiViewport : 'Multi-viewport',
        onePort : 'Single-viewport',
        horizontalSnap : 'Horizontal split screen',
        verticalSnap : 'Vertical split screen',
        tripeSnap : 'Triple viewport',
        quadSnap : 'Four viewport',
        split : 'Split effect',
        splitNONE : 'Split disabled',
        splitLEFT : 'Shielding split left-side',
        splitRIGHT : 'Shielding split right-side',
        splitTop : 'Shielding split up-side',
        splitBOTTOM : 'Shielding split down-side',
        coordinates : 'Coordinate value query',
        queryCoordinates: 'query coordinates',
        underground : 'Underground',
        openUnderground: 'open underground',
        sceneFlood : 'scene floodlight',
        openSceneFlood: 'open scene flood',
        threshold : 'Brightness threshold',
        Intensity : 'Floodlight intensity',
        flyRoute : 'Fly rounte',
        startFly : 'Start',
        pauseFly : 'Pause',
        stopFly : 'Stop',
        observe : 'Observe',
        rotate : 'Rotate(Degree)',
        rotatePoint : 'Rotate around',
        cancelRotatePoint: 'cancel rotate point',
        rotateCirculation : 'Cycle',
        interactive : 'Interaction',
        enableWebcam : 'Enable camera',
        newContent : 'Update content',
        earth : 'Earth',
        shadowMap : 'Shadow',
        sun : 'Sun',
        timeline : 'Timeline',
        brightness : 'Brightness',
        contrast : 'Contrast',
        hue : 'Hue',
        saturation : 'Saturation',
        gamma : 'Gamma',
        layerOptions : 'Layer properties',
        visibility : 'Visibility',
        layerName : 'Layer name',
        shadow: 'shadow',
        shadowMode : 'Shadow mode',
        noShadow : 'No shadow',
        meter : 'Meter',
        degree : 'Degree',
        setSelectionShadow : 'Show selected object shadow',
        setShadow :'Show all object shadows',
        shadowDarkness : 'Shadow shading',
        display : 'Displayable',
        multiSelection : 'Multiple choice',
        cullEnabled : 'Double-sided rendering',
        bReleaseColor :'Free color memory',
        visibleDistanceMin : 'Minimum visible height(Meter)',
        visibleDistanceMax : 'Maximum visible height(Meter)',
        selectEffect: 'select effect',
        selectColorType : 'select color type',
        mix : 'Mixing',
        replace : 'Replace',
        selectColor : 'select color',
        onlyShowSlection : 'Only selected objects are visible',
        onlyHideSlection : 'Only selected objects are hidden',
        showAll : 'show all',
        bottomAltitude : 'Bottom altitude (m)',
        fillStyle : 'Fill style',
        fillMode : 'Fill mode',
        lineMode : 'Wireframe mode',
        fillAndLine : 'Fill and wireframe mode',
        foreColor : 'Foreground',
        lineColor : 'Line color',
        direction : 'Direction',
        roll : 'Roll',
        horizontalFov : 'Horizontal viewing angle (degrees)',
        verticalFov : 'Vertical viewing angle (degrees)',
        visibleColor : 'Visible area color',
        invisibleColor: 'Invisible area color',
        addViewshed : 'Add a visible field',
        clear : 'Clear',
        date : 'Date selection',
        time : 'Time',
        length :'Length(Meter)',
        width : 'Width（Meter）',
        height : 'Height（Meter）',
        firstPoint : 'First point',
        secondPoint : 'Second point',
        thirdPoint : 'Third point',
        startTime : 'Start time',
        endTime : 'End Time',
        extrude: 'Extrude(Meter)',
        extrudeHeight : 'Stretch height (m)',
        sunlight : 'Sunshine effect',
        viewPosition : 'Observation point position',
        additionalHeight : 'Additional height (m)',
        visualRange : 'Visible distance(m)',
        directionAngle : 'Direction angle (degrees)',
        ElevationAngle : 'Pitch angle (degrees)',
        hideenColor : 'Invisible color',
        addViewPoint : 'Add observation point',
        addTarget : 'Add target point',
        displayMode : 'Display mode',
        polyline : 'Line display',
        polygon : 'Polygon display',
        skylinesectorbody : 'Closed volume',
        noOcclusor : 'No closed volume',
        visibleVolume : 'Visible volume',
        novisibleVolume: 'No visible volume',
        skylineColor : 'Skyline color',
        skylineRadius: 'Analysis radius (m)',
        skyline : 'Skyline',
        graphDisplay : '2D display',
        BoxClip : 'Box clip',
        PlaneClip : 'Region clip',
        CrossClip : 'Cross clip',
        ClipModel : 'Clip mode',
        CutInsideBoxFrame : 'Clip inside box with wireframe',
        CutOutBoxFrame : 'Clip outside box with wireframe',
        CutInsideBoxNOFrame : 'Clip inside box without wireframe',
        CutOutBoxNOFrame : 'Clip outside box without wireframe',
        terrainSlope : 'Slope aspect',
        isoline : 'Contour',
        submergeAnalyze : 'Submergence analysis',
        TerrainOperation : 'Terrain operation',
        TilesetEditor : 'Terrain modification',
        analyze : 'Analyze',
        eliminate : 'Clear',
        TerrainMining : 'Terrain excavation',
        TerrainMiningDepth : 'Excavation depth (m)',
        analysisArea : 'Analysis area',
        SpecifyPolygon : 'Specify polygon area',
        AllRegionsAnalysis : 'All regions participate in the analysis',
        AllRegionsNOAnalysis : 'All regions do not participate in the analysis',
        SlopeRange : 'Slope interval',
        minimumGrade : 'Minimum slope (degrees)',
        maximumGrade : 'Maximum slope (degrees)',
        displayStyle : 'Display style',
        fill : 'Filling',
        ShowFillColor : 'Show filling color',
        ShowSlopeArrow : 'Show slope arrow',
        ShowColorArrow : 'Display color and slope arrow',
        transparency : 'Transparency',
        modelTransparency: 'Model Transparency',
        SlopeExplain : '(Slope aspect analysis requires normal terrain)',
        parameterSetting : 'Parameter settings',
        MaximumVisibleElevation : 'Parameter settings',
        MinimumVisibleElevation : 'Minimum visible elevation (m)',
        PlayerSettings : 'Playback settings',
        TheCurrentLevel : 'Current elevation (m)',
        speed : 'Speed (m/s):',
        isolineInterval : 'Equidistance (m)',
        ContourFilling : 'Contour filling',
        panelFilling : 'Contour filling',
        ContourPanelFilling : 'Contour filling',
        noColorTable : 'No color table',
        Add : 'Add',
        AddPoint : 'Add point',
        AddLine : 'Add line',
        AddFaces : 'Add region',
		Thematicmap : 'Thematicmap',
        symbolicLibrary : 'Symbol library',
        conversion : 'Transformation',
        Xrotation : 'Rotate around the X axis(Degree)',
        Yrotation : 'Rotate around the Y axis(Degree)',
        Zrotation : 'Rotate around the Z axis(Degree)',
        zoom : 'Zoom',
        delete : 'Delete',
        polylineSymbolLineColor : 'Line color',
        fulline : 'Solid line',
        Virtuallinear : 'Dotted type',
        contourline : 'Contour line',
        arrowline : 'Arrow line',
        Haloline : 'Halo line',
        Wakeline : 'Tail trace',
        pureColor : 'Solid color',
		ThematicmapColor : 'ThematicmapColor',
        ThematicmapImage : 'ThematicmapImage',
        gridding : 'Grid',
        stripe : 'Stripe',
        serverURl : 'Data service URL',
        serverExplain : '(iserver REST-data service address published synchronously with the model)',
        dataset : 'Dataset',
        DataSourceName : '-----Select datasource name------',
        DataSetName : '-----Select dataset name------',
        TheSpaceField : 'Spatial field',
        Spacelongitude : 'Longitude(Degree)',
        Spacelatitude : 'Latitude(Degree)',
        Spacealtitude : 'Elevation(Meter)',
        StartQuery : 'Start query',
        CleanCharts : 'Clean up the chart',
        home : 'Reset',
        storage : 'Storage',
        share : 'Share',
        sceneSave : 'Scene save',
        storeDate : 'Store date：',
        scenetag : 'Scene label',
        author : 'Author',
        KMLData : 'Local KML data',
		ImageData : 'ImageData',
        OpenLayer : 'Open layer',
        OpenScene : 'Open scene',
        scene : 'Scene',
        clip : 'Clip',
        terrain : 'Terrain',
        onlineEditing : 'Online editing',
        interspaceQuery: 'Spatial query',
        cameraMinimumZoomDistance: 'Camera minimum zoom distance (m)',
        highlightBarrier: 'Highlight obstacle',
        supermapLogo: 'SuperMap Logo',
        removeInvalidTerrainRegion: 'Eliminate invalid terrain regions',
        polygonSymbolColor: 'Polygon symbol color',
        polylineDashSectionLength: 'Dotted component length(Pixel)',
        polylineTrailPeriod: 'Tail trace period(Second)',
        polylineTrailPercent: 'Polyline trail percent',
        polylineSymbolOutlineWdith: 'Outline width(Pixel)',
        pixel: 'Pixel',
        second: 'Second',
        PolygonClip: 'Polygon clip',
        PolygonClipOutside: 'Clip outside',
        PolygonClipInside: 'Clip interior',
        ClipWidth: 'Clip width(Meter)',
        ClipHeight: 'Clip height(Meter)',
        LayerOperation: 'Layer operation',
        ObliquePhotographyExcavation: 'Oblique photography excavation',
        ExecuteExcavation: 'Execute excavation',
        ClearExcavation: 'Clear excavation',
        ObliquePhotographyFlatten: 'Oblique photography flatten',
        ModelFlatten: 'Model flatten',
        ClearFlatten: 'Clear flatten',
        FloodAnalysis: 'Flood analysis',
        MaxHeight: 'Max height（Meter）',
        MinHeight: 'Min height（Meter）',
        FloodSpeed: 'Flood speed(m/s)',
        ExecuteFlood: 'Execute flood',
        ClearFlood: 'Clear flood',
        SelectOffset: 'Select offset',
        OpenSelectOffset: 'Open select offset',
        OffsetX: 'Offset X',
        OffsetY: 'Offset Y',
        offsetZ: 'offset Z',
        LayerColor: 'Layer color',
        FillStyleAndWireFrameMode: 'Fill style and wireframe mode',
        FillStyle: 'Fill style',
        WireFrameMode: 'Wireframe mode',
        LayerFillMode: 'Fill mode',
        LayerWireframeMode: 'Wireframe mode',
        LayerFillAndWireframeMode: 'Fill and wireframe mode',
        TriangleWireframeMode: 'Triangle wireframe',
        QuadWireframeMode: 'Quad wireframe',
        SketchWireframeMode: 'Sketch wireframe',
        PolygonOffset: 'Polygon offset',
        PolygonOffsetFactor: 'Polygon offset factor',
        PolygonOffsetUnit: 'Polygon offset unit',
        SceneSave: 'Scene save',
        SaveDate: 'Save date',
        SceneName: 'Scene name',
        SceneLabel: 'Scene label',
        UpdateCurrentScene: 'Update current scene',
        iEarthScene: 'iEarth scene',
        ShareErrorMsg: 'get scene failed, please login first...',
        ClickToSearchAltitude: 'Click to search altitude',
        UnNamed: 'Unnamed',
        SurfaceTransparency: 'Surface transparency',
        Version: 'Version',
        WhatsNew: "1、Add the polygon clipping function module\n"+
        "2、Add the Cross clip function module\n"+
        "3、The S3M layer supports fill style and wireframe mode selection\n"+
        "4、The S3M layer allows you to select offsets\n"+
        "5、S3M layer supports model color control\n"+
        "6、The S3M layer supports flooding analysis on the model\n"+
        "7、The S3M layer supports polygon migration\n"+
        "8、Increase the contour width of line symbol, the length of component of dash line, the period of wakes, and the proportion of wakes\n"+
        "9、Support surface symbols to set colors\n",
        baseLayerSource: 'base layer source',
        localImage: 'local image',
        bingMaps: 'Bing Maps',
        tianditu: 'Map world',
        OpenStreetMap: 'Open Street Map',
        SuperMapChinaDark: 'SuperMap China dark',
        gridImagery: 'grid imagery',
        superMapChinaLight: 'SuperMap China light',
        useRoller: 'Use roller',
        lrRoller: 'Left-right roller',
        leftRoller: 'Hide left',
        rightRoller: 'Hide right',
        tbRoller: 'Top-bottom roller',
        topRoller: 'Hide top',
        bottomRoller: 'Hide bottom',
        imageryRoller: 'Imagery roller',
        windParticle: 'Wind particle',
        trailLines: 'Trail lines',
        scanLine: 'Scan line',
        saveAs: 'Save as',
        saveErrorWhileSceneEmpty: 'The save scene name cannot be empty!',
        saveSceneSuccess: 'Save scene success！',
        saveSceneFailed: 'Storage scene failed! please login to iPortal or Online account...',
        updateSceneSuccess: 'Scene update success！',
        updateSceneFailed: 'Scene update failed. save the current scene first',
        layerUrl: 'Layer URL',
        layerName: 'Layer name',
        sceneUrl: 'Scene url',
        fullScreen: 'Full screen',
        polygonClipMode: 'Clip mode',
        clickToSearchCoordination: 'Click to search coordination',
        stop: 'Stop',
        stopChoose: 'Stop choose',
        searchPlaceHolder: 'Enter an address or landmark...',
        urlMismatchingPattern: 'Please enter the correct URL format',
        polygonSymbolGridCellAlpha: 'Grid cell alpha',
        polygonSymbolGridLineCount: 'Grid line count',
        polygonSymbolGridLineThickness: 'Grid line thickness',
        polygonSymbolGridLineOffset: 'Grid line offset',
        polygonSymbolStripeEvenColor: 'Even stripe color',
        polygonSymbolStripeOddColor: 'Odd stripe color',
        polygonSymbolStripeOffset: 'Stripe offset',
        polygonSymbolStripeOrientation: 'Stripe orientation',
        polygonSymbolStripeRepeat: 'Stripe repeat',
        horizontal: 'Horizontal',
        vertical: 'Vertical',
        draw: 'Draw',
        polylineSymbolGapColor: 'Gap color',
        polylineSymbolOutlineColor: 'Outline color',
        polylineSymbolGlowPower: 'Glow power',
        polylineSymbolLineWidth: 'Line width(px)',
        pointSymbolColor: 'Point symbol color',
        highlightBarrierColor: 'Highlight barrier color',
        fullScreenToggle: 'Full screen toggle',
        light: 'Light',
		ParticleSystem: 'Particle system',
        Fire:'Fire',
        Fountain:'Fountain',
        pointLight: 'Point light',
        spotLight: 'Spot light',
        directionalLight: 'Directional light',
        cutoffDistance: 'Cutoff distance',
        decay: 'Decay',
        intensity: 'Intensity',
        lightSourceColor: 'Light source color',
        spotLightAngle: 'Angle',
        addToken: 'Add token',
        loadException: 'Load failed, please check data or token',
        obliqueLightWarning: 'Note: oblique photographic data has no lighting effect',
        hdr: 'High dynamic range',
        emissionRate:'Emission rate',
        particleSize:'Particle size',
        minimumParticleLife:'Minimum particle life',
        maximumParticleLife:'Maximum particle life',
        minimumSpeed:'Minimum speed',
        maximumSpeed:'Maximum speed',
        startScale:'Start scale',
        endScale:'End scale',
        gravity:'Gravity',
        LaunchType:'Launch type',
        CircularRadiation:'Circular radiation',
        SpheroidRadiation:'Spheroid radiation',
        ConicalRadiation:'Conical radiation',
        BoxedRadiation:'Boxed radiation',
		TwoDimensionalSkyline:'2D skyline',
        LayerRepeat:'This layer already exists, please do not load it repeatedly!',
        SCTFailed:'SCT URL error, terrain loading failed!',
        RightClickToDisplay:'Right click to display / set the layer properties',
        notSupportTerrain:'Note: terrain profile analysis is not supported temporarily',
        heatMap: 'HeatMap',
    };
    return ResourceEN;
});