define([],function(){
    var ResourceCN = {
        login : '登陆',
        logout : '登出',
        account : '我的账户 :',
        save : '保存',
        exit : '退出',
        myMsg : '我的消息 :',
        uploadData : '上传数据',
        name : '名称',
        address : '地址',
        aqiTitle : 'PM2.5指数实时查询',
        stkTerrain : 'STK在线地形',
        title : '标题',
        confirm : '确定',
        cancel : '取消',
        objectEditor : '对象编辑',
        description : '描述',
        compass : '罗盘',
        s3mLayer : 'S3M图层',
        imageryLayer : '影像图层',
        terrainLayer : '地形图层',
        sctTerrainLayer : 'SCT地形图层',
        featureQuery : '属性查询',
        selDataSource : '请选择数据源',
        selDataSet : '请选择数据集',
        urlNotNullMsg : 'URL不能为空，请输入url!',
        layerNameNotNullMsg : '图层名称不能为空，请输入图层名称!',
        location : '定位',
        notSupportLocation : '您的浏览器不支持获取位置信息功能！',
        layerList : '图层列表',
        confirmDelLayer : '是否确定删除该图层？',
        kmlLayer : 'KML图层',
        markerLayer : 'MARKER图层',
        selLocalFile : '选择本地文件',
        measureArea : '测面',
        measureDis : '测距',
        close : '关闭',
        measure : '量算',
        kmUnit : '千米',
        mUnit : '米',
        distance : '距离',
        sqkmUnit : '平方公里',
        sqmUnit : '平方米',
        area : '面积',
        smOnlineService : '超图云服务',
        customService : '自定义服务',
        localKML : '本地KML',
        skyAtmosphereEffect : '大气渲染',
        lightEffect : '光照渲染',
        fogEffect : '雾化效果',
        layerManager : '图层管理',
        expand : '展开',
        addLayer : '添加图层',
        setBaseLayer : '底图设置',
        addMarker : '添加MARKER',
        setEffect : '渲染设置',
        fold : '收起',
        publicService : '公共服务',
        mycontent : '我的内容',
        imgServiceType : '图片(默认影像)',
        bingServiceType : 'BingMap全球影像服务',
        tdtServiceType : '天地图全球影像服务',
        osmServiceType : 'openstreetmap地图',
        tianditu : '天地图',
        layerExistMsg : '该图层已经存在，请勿重复加载!',
        imgUrlErrorMsg : '影像服务URL错误，影像加载失败！',
        scpUrlErrorMsg : 'SCP URL地址错误，S3M图层加载失败！',
        visualization:'可视化',
        splitSrc:'卷帘对比',
        animationLand:'陆地温度异常变化',
        workspaceSaveOK : '工作空间保存成功！',
        workspaceSaveFail : '工作空间保存失败',
        depthAgainst : '深度检测'
    };
    return ResourceCN;
});