define([],function(){
    var ResourceEN = {
        login : 'Login',
        logout : 'Logout',
        account : 'My Account: ',
        save : 'Save',
        exit : 'Exit',
        myMsg : 'My News: ',
        uploadData : 'Upload',
        name : 'Name',
        address : 'Address',
        aqiTitle : 'PM2.5 real-time query',
        stkTerrain : 'STK Online Terrain',
        title : 'Title',
        confirm : 'OK',
        cancel : 'Cancel',
        objectEditor : 'Object Edit',
        description : 'Des',
        compass : 'Compass',
        s3mLayer : 'S3M Layer',
        imageryLayer : 'Image Layer',
        terrainLayer : 'Terrain Layer',
        sctTerrainLayer : 'SCT Terrain Layer',
        featureQuery : 'Attribute Query',
        selDataSource : 'Please select the datasource ',
        selDataSet : 'PLease select the dataset',
        urlNotNullMsg : 'URL can not be bull. Please input the url!',
        layerNameNotNullMsg : 'The layer name can not be null. Please input the layer name!',
        location : 'Location',
        notSupportLocation : 'Your browser does not support the location information function!',
        layerList : 'Layer List',
        confirmDelLayer : 'Are you sure you want to delete this layer?',
        kmlLayer : 'KML Layer',
        markerLayer : 'MARKER Layer',
        selLocalFile : 'Select the local file',
        measureArea : 'Measure Area',
        measureDis : 'Measure Distance',
        close : 'Close',
        measure : 'Measure',
        kmUnit : 'Kilometer',
        mUnit : 'Meter',
        distance : 'Distance',
        sqkmUnit : 'square kilometers',
        sqmUnit : 'square meter',
        area : 'Area',
        smOnlineService : 'SuperMap Cloud Service',
        customService : 'Custom Service',
        localKML : 'Local KML',
        skyAtmosphereEffect : 'Atmosphere Rendering',
        lightEffect : 'Light Rendering',
        fogEffect : 'Atomization Effect',
        layerManager : 'Layer Manager',
        expand : 'Expand',
        addLayer : 'Add Layer',
        setBaseLayer : 'Base Layer Settings',
        addMarker : 'Add MARKER',
        setEffect : 'Render Settings',
        fold : 'Fold',
        publicService : 'Public Service',
        mycontent : 'My Content',
        imgServiceType : 'Image',
        bingServiceType : 'BingMap Global Image Service',
        tdtServiceType : 'Tianditu Global Iage Service',
        osmServiceType : 'openstreetmap Map',
        tianditu : 'Tianditu',
        layerExistMsg : 'The layer exists already, please do not repeat loading!',
        imgUrlErrorMsg : 'The image ervice URL is error. Failed to load the image!',
        scpUrlErrorMsg : 'SCP URL address is error. Failed to load the S3M layer!',
        visualization:'visualization',
        splitSrc:'SplitSrcreen',
        animationLand:'Land Temperature change anomaly',
        workspaceSaveOK : 'Save the workspace successfully!',
        workspaceSaveFail : 'Failed to save the workspace',
        depthAgainst:'Depth Against'
    };
    return ResourceEN;
});