// import { zhCN, dateZhCN } from 'naive-ui'

export default {
    Type:'zh',
    // NaiveLocale:zhCN,
    // NaiveDateLocale:dateZhCN,
    Analyze: '分析',
    Clip: '裁剪',
    Clear: '清除',
    Meter_second: '米/秒',
    Meter: '米',
    VisiblePositions:'坐标显示',
    Longitude: '经度',
    Latitude: '纬度',
    Altitude: '高程',
    Delete:'删除',
    NoLayer:'暂无图层',
    S3mLayer:'s3m图层',
    ImageLayer:'影像图层',
    TerrainLayer:'地形图层',
    DeleteLayerTip:'确定要删除此图层吗？',
    DeleteLayerFail:'删除图层成失败！',
    DeleteLayerSuccess:'删除图层成功！',
    Sightline:'通视分析',
    Skyline:'天际线分析',
    Viewshed:'可视域分析',
    SceneAlreadyExists:'场景已存在！',
    AddLayerFail:'添加图层失败！',
    AddLayerSuccess:'添加图层成功！',
    LayerUrl:'图层URL',
    LayerName:'图层名称',
    Confirm:'确认',
    LayerAddressTip:'图层地址不能为空！',
    LayerNameTip:'图层名称不能为空！',
    Mvt:'矢量瓦片',
    Scene:'场景',
    CheckLayerTypeError:'请检查添加类型是否正常？',
    AddToken:'添加token（选填）',
    ISct:'是否iserver发布',
    Mode:'模式',
    SpaceMeasure:'空间量算',
    LandMeasure:'贴地量算',
    CGCS2000:'CGCS2000',
    XIAN80:'XIAN80',
    WGS84:'WGS84',
    PlaneProjection:'平面投影',
    MeasureDistance:'测距',
    MeasureHeight:'测高',
    MeasureSurface:'测面',
    VertexSnap:'顶点捕捉',
    ShowContour:'显示等高线',
    DisplayVisualsBody: '显示可视体',
    DisplayInvisibleBody: '显示不可视体',
    ViewshedAnimation:'动态可视域',
    VerticalFov:'垂直视角',
    HorizontalFov:'水平视角',
    VisibleAreaColor:'可视区颜色',
    HiddenAreaColor:'不可视颜色',
    DirectionAngle:'方向角',
    PitchAngle:'俯仰角',
    ClipModel:'裁剪模式',
    PlaneDirection:'平面方向',
    ClipFaceShow:'显示裁剪面',
    Zoom:'缩放',
    DirectionByNormal:'沿法线方向',
    ClipInside:'裁剪内部',
    ClipOutside:'裁剪外部',
    Xrotation: '绕X轴旋转',
    Yrotation: '绕Y轴旋转',
    Zrotation: '绕Z轴旋转',
    ClipWidth: '裁剪宽度',
    ClipHeight: '裁剪高度',
    StretchingHeight:'拉伸高度',
    MaxVisibleHeight:'最大可见高程',
    MinVisibleHeight:'最小可见高程',
    Equidistance:'等值距',
    window:'线颜色',
    DisplayMode:'显示模式',
    EditAnalysisArea:'编辑区域',
    IsolineFill:'等高线填充',
    IsosurfaceFill:'等高面填充',
    IsolineSurfaceFill:'等高线和面填充',
    NoColorTable:'无颜色表',
    CurrentHeight:'当前高程',
    Transparency:'透明度',
    Speed:'速度',
    AnalysisArea:'分析区域',
    MaxSlope:'最大坡度',
    MinSlope:'最小坡度',
    SpecifyPolygon:'指定区域参与分析',
    AllRegions:'所有区域参与分析',
    NoRegions:'没有区域参与分析',
    ArrowAndFaceDisplay:'箭头和面显示',
    FaceDisplay:'面显示',
    ArrowDisplay:'箭头显示',
    EditZ:'编辑z轴方向',
    TerrainDig:'地形开挖',
    TerrainModify:'地形修改',
    ExcavationDepth:'开挖深度',
    AnalysisRadius:'分析半径',
    LineWidth:'线宽度',
    SkylineColor:'天际线颜色',
    SkylineBodyColor:'天际体颜色',
    ObstacleColor:'障碍物颜色',
    Display2D:'二维显示',
    HighlightObstacles:'高亮障碍物',
    GlobeNoAnalysis:'地表不参与分析',
    LineDisplay:'线显示',
    BodyDisplay:'体显示',
    ShowObstaclesPOints:'显示障碍点',
    InvisibleAreaColor:'不可见颜色',
    ShowBarrierPoints:'显示障碍点',
    TimeInterval:'时间间隔',
    Space:'间距',
    BottomHeight:'底部高程',
    ShowShadow:'开启阴影',
    StartTime:'开始时间',
    EndTime:'结束时间',
    FilterInterval:'过滤区间',
    DaylightingRate:'采光率',
    Start:'开始',
    Pause:'暂停',
    Stop:'停止',
    DataUrl:'数据服务地址：...rest/data',
    DatasetNames:'数据源:数据集,查询属性',
    AttributeShow:'属性展示',
    GlobeHide:'隐藏地球',
    Spacing:'间隔距离',
    SpeedRatio:'旋转速度',
    FlyCircleLoop:'循环旋转',
    FlyCircle:'绕点旋转',
    FlyingAlong:'沿线飞行',
    FlightRouteAddress:'飞行路线地址',
    Folder:'文件夹',
    StopSelection:'站点选择',
    ShowRoute:'显示路线',
    ShowStop:'显示站点',
    SymbolType:'符号类型',
    AddType:'添加类型',
    SymbolColor:'符号颜色',
    Amount:'数量',
    AddBypoint:'单个添加',
    AddByline:'沿线添加',
    AddByFace:'区域添加',
    Add:'添加',
    DrawMode:'绘制模式',
    SpaceMode:'空间模式',
    TERRAINMode:'贴地模式',
    S3M_TILEMode:'贴S3M模式',
    BOTHMode:'同时贴地贴对象',
    DottedColor:'间隔颜色',
    DottedLength:'分量长度',
    OutLineColor:'轮廓颜色',
    OutLineWidth:'轮廓宽度',
    GlowStrength:'光晕强度',
    LineColor:"线颜色",
    TrailPercentage:'尾迹占比',
    Edit:'编辑',
    FaceColor:'面颜色',
    GridWidth:'网格线宽',
    GridCount:'网格线数',
    GridCellAlpha:'单元透明度',
    StripeEvenColor:'偶数带颜色',
    StripeOddColor:'基数带颜色',
    StripeRepeat:'带条重复数',
    StripeOffset:'带条偏移量',
    StripeOrientation:'带条方向',
    SplitScreenMode:'分屏模式',
    NoneSplit:'不分屏',
    HorizontalSplit:'水平分屏',
    VerticallySplit:'垂直分屏',
    TripleSplit:'三视口',
    QuadSplit:'四视口',
    ViewportOne:'视口一',
    ViewportTwo:'视口二',
    ViewportThree:'视口三',
    ViewportFour:'视口四',
    RollerMode:'卷帘模式',
    NoUseRoller:'不使用卷帘',
    LeftRightRoller:'左右卷帘',
    TopBottomRoller:'上下卷帘',
    CustomRoller:'自定义卷帘',
    ShieldLeft:'屏蔽左侧',
    ShieldRight:'屏蔽右侧',
    ShieldTop:'屏蔽上侧',
    ShieldBottom:'屏蔽下侧',
    LightColor:'光源颜色',
    LightIntensity:'光源强度',
    CutoffDistance:'扩散距离',
    DecayFactor:'衰减因子',
    SpotLightAngle:'聚光范围',
    PointLight:'点光源',
    SpotLight:'聚光灯',
    ParallelLight:'平行光',
    Globe:'地球',
    Sun:'太阳',
    ShadowMap:'阴影',
    AtomsphereRender:'大气渲染',
    FogEffect:'雾化效果',
    DepthAgainst:'深度检测',
    Underground:'开启地下',
    FrameRate:'帧率',
    Cloud:'云层',
    SkyBox:'天空盒',
    Rain:'雨景',
    Snow:'雪景',
    Timeline:'时间轴',
    Compass:'罗盘',
    FullScreen:'全屏',
    Animation:'动画',
    Search:'搜索',
    PositionReset:'初始视图',
    ViewMode:'视图模式',
    SurfaceTransparency:'地表透明度',
    SelectedLayer:'选择图层',
    Brightness:'亮度',
    Contrast:'对比度',
    Hue:'色调',
    Saturation:'饱和度',
    Gamma:'伽马',
    CloseShadow:'关闭阴影',
    OpenShadow:'开启阴影',
    ShadowDarkness:'阴影明暗度',
    SelectEnabled:'是否可选',
    MultiChoose:'多选',
    CullEnabled:'双面渲染',
    Visibility:'可见性',
    OnlyShowSlection: '仅选中对象可见',
    OnlyHideSlection: '仅选中对象隐藏',
    ShowAll: '显示全部',
    ForeColor: '前景色',
    SelectedColor: '选中色',
    SelectColorMix: '选中色混合',
    SelectColorReplace: '选中色替换',
    BottomAltitude: '底部高层',
    LayerTrans: '图层透明度',
    FillStyle: '填充风格',
    Fill: '填充模式',
    WireFrame: '线框模式',
    FillWireframe: '填充和线框模式',
    visibleDistanceMin: '最小可见距离',
    VisibleDistanceMax: '最大可见距离',
    Selectedoffset: '选中偏移',
    OffsetX: '沿X轴偏移',
    OffsetY: '沿Y轴偏移',
    OffsetZ: '沿Z轴偏移',
    PolygonOffset: '多边形偏移',
    PolygonOffsetFactor: '偏移因子',
    PolygonOffsetUnit: '偏移量',
    Excavation: '开挖',
    Flatten: '压平',
    ObliquePhotographyModel: '倾斜摄影模型',
    TransparentColor: '透明色',
    TransparencyTolerance: '透明容限',
    LineScan: '线状扫描',
    CircularScan: '环状扫描',
    ScanColor: '扫描颜色',
    ScanTexture: '扫描纹理',
    ScanMode: '扫描模式',
    ScanPeriod: '扫描周期',
    ScanSpeed: '扫描速度',
    ScanWidth: '扫描宽度',
    NoTexture: '无纹理',
    ParticleType: '粒子类型',
    Flame: '立体火',
    Fireworks:'烟花',
    RingFire: '环形火',
    FlowFire: '流淌火',
    ExplosionFire: '爆炸火',
    Fountain: '喷泉',
    FireWater: '消防水',
    RingRadius: '环形半径',
    EmissionRate: '粒子数量',
    ParticleSize: '粒子大小',
    ParticleLife: '生命周期',
    SpeedRange: '速度范围',
    StartScale: '初始比例',
    EndScale: '终止比例',
    Gravity: '重力',
    GridImage:'网格影像',


    


    ShadowStartTip:'播放一天时间段内阳光和阴影动画',
    ShadowStartTip2:'播放一年的阳光和阴影动画',
    ShadowStopTip:'停止动画',
    ViewshedTip:'绘制模型运动路线，鼠标右键结束',
    ClipBoxTip:'先绘制盒子底部，再移动鼠标绘制盒子高度，鼠标右键结束',
    ClipPlaneTip:'绘制一条线段确认平面位置，鼠标右键结束',
    LayerAnimationTip:"拖拽图层可进行排序",
    LocaleDataKML:'本地KML数据',
    DrawSymbolTip:'鼠标左键开始添加，右键结束，选中对象编辑',
    DrawlineTip:'鼠标左键选中绘制对象进行编辑',
    LightTip:'鼠标左键绘制两点确定光源方向，右键结束',
    ScanEffectTip:'鼠标左键绘制两点确定扫描线方向，右键结束',
    
}
